package pluginmanifest

import (
	"os"
	"path/filepath"
	"strings"
)

func buildRootReadmeArtifact(root string, layout authoredLayout, manifest Manifest) (*Artifact, error) {
	authoredReadme := layout.Path("README.md")
	authoredReadmePath := filepath.Join(root, authoredReadme)
	if _, err := os.Stat(authoredReadmePath); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	managed, err := shouldManageRootReadme(root)
	if err != nil {
		return nil, err
	}
	if !managed {
		return nil, nil
	}
	title := strings.TrimSpace(manifest.Name)
	if title == "" {
		title = "plugin"
	}
	var body strings.Builder
	body.WriteString(managedRootReadmeSentinel)
	body.WriteString("\n")
	body.WriteString("# ")
	body.WriteString(title)
	body.WriteString("\n\n")
	body.WriteString("This file is generated by `plugin-kit-ai generate`.\n")
	body.WriteString("Do not edit it by hand. Edit files under `")
	body.WriteString(layout.Path(""))
	body.WriteString("/`, especially [`")
	body.WriteString(authoredReadme)
	body.WriteString("`](./")
	body.WriteString(authoredReadme)
	body.WriteString(").\n\n")
	body.WriteString("Start here:\n\n")
	body.WriteString("- full plugin guide: [`")
	body.WriteString(authoredReadme)
	body.WriteString("`](./")
	body.WriteString(authoredReadme)
	body.WriteString(")\n")
	body.WriteString("- boundary instructions for humans and agents: [`AGENTS.md`](./AGENTS.md)\n")
	body.WriteString("- generated root output inventory: [`GENERATED.md`](./GENERATED.md)\n\n")
	body.WriteString("This plugin root is the native/generated output surface for the supported targets.\n")
	artifact := Artifact{RelPath: "README.md", Content: []byte(body.String())}
	return &artifact, nil
}

func shouldManageRootReadme(root string) (bool, error) {
	body, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, err
	}
	text := normalizeManagedText(string(body))
	return strings.Contains(text, managedRootReadmeSentinel) || strings.Contains(text, legacyManagedReadmeLine), nil
}
