package pluginmanifest

import (
	"strings"
)

const (
	managedGuidanceStart      = "<!-- plugin-kit-ai:begin managed-guidance -->"
	managedGuidanceEnd        = "<!-- plugin-kit-ai:end managed-guidance -->"
	managedRootReadmeSentinel = "<!-- plugin-kit-ai:managed-root-readme -->"
	legacyManagedReadmeLine   = "This file is generated by `plugin-kit-ai generate`."
)

func normalizeManagedText(body string) string {
	body = strings.ReplaceAll(body, "\r\n", "\n")
	body = strings.ReplaceAll(body, "\r", "\n")
	return body
}
