package pluginmanifest

import (
	"path/filepath"
	"strings"

	"github.com/777genius/plugin-kit-ai/cli/internal/publicationexec"
	"github.com/777genius/plugin-kit-ai/cli/internal/publishschema"
)

func buildRootGeneratedGuideArtifact(root string, layout authoredLayout, graph PackageGraph, publication publishschema.State) (*Artifact, error) {
	paths, err := generatedArtifactInventory(root, layout, graph, publication, graph.Manifest.EnabledTargets())
	if err != nil {
		return nil, err
	}
	var body strings.Builder
	body.WriteString("# Generated Outputs\n\n")
	body.WriteString("This file is generated by `plugin-kit-ai generate`.\n")
	body.WriteString("Do not edit the paths below by hand. Edit only `")
	body.WriteString(layout.Path(""))
	body.WriteString("/`, then regenerate.\n\n")
	body.WriteString("This inventory covers the full plugin package across all enabled targets.\n\n")
	body.WriteString("## Boundary Docs\n\n")
	body.WriteString("These committed root docs are guidance files with a managed block, not plain generated outputs:\n\n")
	for _, rel := range boundaryDocsForLayout(layout) {
		body.WriteString("- `")
		body.WriteString(rel)
		body.WriteString("`\n")
	}
	body.WriteString("\n## Managed Generated Outputs\n\n")
	if managesReadme, err := shouldManageRootReadme(root); err != nil {
		return nil, err
	} else if managesReadme {
		body.WriteString("`README.md` is a generated root entrypoint that points readers to `")
		body.WriteString(layout.Path("README.md"))
		body.WriteString("`.\n\n")
	}
	for _, rel := range paths {
		body.WriteString("- `")
		body.WriteString(rel)
		body.WriteString("`\n")
	}
	body.WriteString("\n## Refresh\n\n")
	body.WriteString("```bash\n")
	body.WriteString("plugin-kit-ai normalize .\n")
	body.WriteString("plugin-kit-ai generate .\n")
	body.WriteString("plugin-kit-ai generate --check .\n")
	body.WriteString("```\n")
	return &Artifact{RelPath: "GENERATED.md", Content: []byte(body.String())}, nil
}

func generatedArtifactInventory(root string, layout authoredLayout, graph PackageGraph, publication publishschema.State, selected []string) ([]string, error) {
	artifactMap := map[string]struct{}{}
	boundarySet := map[string]struct{}{}
	for _, rel := range boundaryDocsForLayout(layout) {
		boundarySet[filepath.ToSlash(filepath.Clean(rel))] = struct{}{}
	}
	for _, target := range selected {
		generated, err := renderTargetArtifacts(root, graph, target)
		if err != nil {
			return nil, err
		}
		for _, artifact := range generated {
			rel := filepath.ToSlash(filepath.Clean(artifact.RelPath))
			if _, skip := boundarySet[rel]; skip {
				continue
			}
			artifactMap[rel] = struct{}{}
		}
	}
	publicationArtifacts, err := publicationexec.Generate(graph, publication, selected)
	if err != nil {
		return nil, err
	}
	for _, artifact := range publicationArtifacts {
		artifactMap[filepath.ToSlash(filepath.Clean(artifact.RelPath))] = struct{}{}
	}
	if readme, err := buildRootReadmeArtifact(root, layout, graph.Manifest); err != nil {
		return nil, err
	} else if readme != nil {
		artifactMap[readme.RelPath] = struct{}{}
	}
	artifactMap["GENERATED.md"] = struct{}{}
	return sortedKeys(artifactMap), nil
}
