"use strict";
if (process.env.AGENTPLUGINS_STAGED_TEST_CHILD === "1") {
  require("node:test")("source-checkout-only suite", { skip: "requires the complete repository source tree" }, () => {});
} else {
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const harness=require("../scripts/milestone-a-e2e"),HEAD="9db754c93c713219c72206eab54d71ee39e88abf";
const D="sha256:"+"a".repeat(64),R="sha256:"+"b".repeat(64),P="sha256:"+"c".repeat(64);
const repo=path.resolve(__dirname,"../../.."),workflow=fs.readFileSync(path.join(repo,".github/workflows/authoring-milestone-a-e2e.yml"),"utf8");
test("prepare assembles the exact current stager identity schema",()=>{const identity=harness.candidateIdentity(HEAD);assert.deepEqual(identity,{repository:"777genius/universal-agent-plugins",commit:HEAD,engine_revision:HEAD,versions:{agentplugins:"0.1.91","plugin-kit-ai":"2.0.0"}});assert.notEqual(identity.versions.agentplugins,identity.versions["plugin-kit-ai"]);});
test("negative metadata mutation is rejected by the real stager validator",()=>{const identity=harness.candidateIdentity(HEAD);delete identity.engine_revision;const c=require("../scripts/dual-authoring-candidate");assert.throws(()=>c.identity(identity),/identity: unexpected or missing fields/);});
test("trusted tool config resolves setup-node-style npm and Go symlinks to invocable regular files",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-tools-"));try{const npmCli=path.join(root,"lib/node_modules/npm/bin/npm-cli.js"),goTarget=path.join(root,"toolchains/go/bin/go");fs.mkdirSync(path.dirname(npmCli),{recursive:true});fs.mkdirSync(path.dirname(goTarget),{recursive:true});fs.writeFileSync(npmCli,'if(process.argv[2]!=="--probe")process.exit(19);process.stdout.write("npm-cli-ok")');fs.writeFileSync(goTarget,"go-binary-placeholder");const npmLink=path.join(root,"bin/npm"),goLink=path.join(root,"bin/go");fs.mkdirSync(path.dirname(npmLink));fs.symlinkSync(path.relative(path.dirname(npmLink),npmCli),npmLink);fs.symlinkSync(path.relative(path.dirname(goLink),goTarget),goLink);const tools=harness.resolveTrustedTools(goLink,npmLink,process.execPath);assert.equal(tools.go,fs.realpathSync(goTarget));assert.equal(tools.npm,fs.realpathSync(npmCli));assert.equal(tools.node,fs.realpathSync(process.execPath));for(const value of Object.values(tools)){const stat=fs.lstatSync(value);assert.equal(stat.isFile(),true);assert.equal(stat.nlink,1)}assert.equal(require("node:child_process").execFileSync(tools.node,[tools.npm,"--probe"],{encoding:"utf8"}),"npm-cli-ok");}finally{fs.rmSync(root,{recursive:true,force:true})}});
test("trusted tool config rejects a genuinely aliased canonical tool with its label",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-aliased-tool-"));try{const tool=path.join(root,"go"),alias=path.join(root,"go-alias");fs.writeFileSync(tool,"not-empty");fs.linkSync(tool,alias);assert.throws(()=>harness.canonicalTool("go",tool),/^Error: go canonical tool must be regular, nonempty, bounded and unaliased$/);}finally{fs.rmSync(root,{recursive:true,force:true})}});
test("precreated failure root stays uploadable while candidate starts absent",()=>{const outer=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-prepare-failure-")),root=path.join(outer,"artifact"),evidence=path.join(root,"evidence");try{fs.mkdirSync(evidence,{recursive:true,mode:0o700});assert.throws(()=>harness.prepare({root,precreatedRoot:true,repo,expectedHead:"0".repeat(40)}),/expected exact candidate/);assert.equal(fs.statSync(root).mode&0o777,0o700);assert.equal(fs.statSync(evidence).mode&0o777,0o700);assert.equal(fs.existsSync(path.join(root,"candidate")),false);const receipt=JSON.parse(fs.readFileSync(path.join(evidence,"prepare-failure.json")));assert.equal(receipt.candidate_present,false);assert.equal(receipt.publication,false);}finally{fs.rmSync(outer,{recursive:true,force:true});}});
function fixture(options={}){const outer=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-exec-")),input=path.join(outer,"input"),logs=path.join(outer,"declared-logs");fs.mkdirSync(input);fs.mkdirSync(logs);fs.mkdirSync(path.join(input,"candidate"));const entrypoints={};
 for(const product of ["agentplugins","plugin-kit-ai"]){const pkg=path.join(outer,`package-${product}`),bin=path.join(pkg,"bin");fs.mkdirSync(bin,{recursive:true});fs.writeFileSync(path.join(pkg,"package.json"),JSON.stringify({name:product,version:"2.0.0",...(options.stagedProvenance?{}:{gitHead:options.packageRevision||HEAD})}));if(options.stagedProvenance){fs.writeFileSync(path.join(bin,"package.json"),JSON.stringify({type:"commonjs"}));fs.writeFileSync(path.join(pkg,"private-release.json"),JSON.stringify({schema:"dual-authoring-npm/v1",identity:{commit:options.packageRevision||HEAD}}));}const ep=path.join(bin,`${product}.js`);fs.writeFileSync(ep,`#!/usr/bin/env node
const fs=require('node:fs'),p=require('node:path');
const product=${JSON.stringify(product)},a=process.argv.slice(2),author=a[0]==='author',v=author?a[1]:a[0],project=v==='add'?process.cwd():(author?a[2]:a[1]);
const required=['HOME','USERPROFILE','TMPDIR','TMP','TEMP','XDG_CONFIG_HOME','XDG_CACHE_HOME','XDG_DATA_HOME','XDG_STATE_HOME','APPDATA','LOCALAPPDATA','npm_config_cache','npm_config_prefix','CODEX_HOME'];
if(!required.every(k=>process.env[k]&&process.env[k].startsWith(p.dirname(process.env.HOME))))process.exit(17);
if(${JSON.stringify(options.requireCandidateCache||false)}&&(!fs.statSync(process.env.UAP_PRIVATE_NPM_CACHE).isDirectory()||process.env.UAP_PRIVATE_NPM_CACHE!==p.join(p.dirname(process.env.HOME),'cache','candidate')))process.exit(18);
if(${JSON.stringify(options.requireDestinationAbsent||false)}&&v==='init'&&fs.existsSync(project))process.exit(19);
fs.appendFileSync(${JSON.stringify(path.join(logs,product+".jsonl"))},JSON.stringify({argv:a,env:Object.fromEntries(required.map(k=>[k,process.env[k]]))})+'\\n');
if(${JSON.stringify(options.failAdd||false)}&&v==='add'){process.stdout.write('complete stdout diagnostic');process.stderr.write('complete stderr diagnostic');process.exit(23);}
if(${JSON.stringify(options.failValidate||false)}&&v==='validate'){process.stdout.write('validate stdout diagnostic');process.stderr.write('validate stderr diagnostic');process.exit(29);}
if(v==='init'){fs.mkdirSync(project);fs.writeFileSync(p.join(project,'fixture.txt'),'same');}
let data={revision:${JSON.stringify(options.resultRevision===null?null:(options.resultRevision||HEAD))},operation:v};if(data.revision===null)delete data.revision;
if(v==='add'){const tree=${JSON.stringify(D)},manifest=${JSON.stringify(R)};const plan={client_id:${JSON.stringify(options.wrongTarget?"claude":"codex")},scope:'user',status:'manual_activation_required',package_mode:'managed_projection',activation:'manual_activation_required',authentication:'not_checked',policy:'allowed',verification:'package_valid',physical_artifact_id:'fixture',components:[{kind:'skill',name:'milestone-a-fixture',support:'projected'}]};const output={revision:${JSON.stringify(options.resultRevision===null?null:(options.resultRevision||HEAD))},plugin:'milestone-a-fixture',source:project,tree_digest:tree,manifest_digest:manifest,dry_run:true,result:{installation_id:'',plan,requires_confirmation:true,mutated:false}};if(output.revision===null)delete output.revision;data={batch:true,status:'planned',succeeded:1,failed:0,revision:${JSON.stringify(options.resultRevision===null?null:(options.resultRevision||HEAD))},plugin:'milestone-a-fixture',source:project,tree_digest:tree,manifest_digest:manifest,dry_run:true,security:{schema_version:1,subject:{tree_digest:tree,manifest_digest:manifest},scanner:{id:'lintai',version:'0.1.3'},policy:{id:'agent-plugin-install',version:2,digest:${JSON.stringify(P)}},outcome:'no_blocking_findings',counts:{blocking:0,warnings:0,total:0},scanned_files:4,report_digest:${JSON.stringify(D)},evidence_source:'local_scan'},targets:[{target:${JSON.stringify(options.wrongRequestedTarget?"claude":"codex")},status:'manual_activation_required',output}]};if(${JSON.stringify(options.noSecurity||false)})delete data.security;if(${JSON.stringify(options.failedSecurity||false)}){data.security.outcome='blocking_findings';data.security.counts={blocking:1,warnings:0,total:1}}if(${JSON.stringify(options.destination||"")})plan.destination=${JSON.stringify(options.destination||"")}.replace('<CODEX_HOME>',process.env.CODEX_HOME).replace('<JOURNEY>',p.dirname(process.env.HOME));if(data.revision===null)delete data.revision;}
if(${JSON.stringify(options.outside||false)}&&v==='validate')data.output_root=p.join(p.dirname(p.dirname(process.env.HOME)),'sibling');
if(${JSON.stringify(options.mismatch||false)}&&product==='plugin-kit-ai'&&v==='validate')data.changed=true;
process.stdout.write(JSON.stringify({schema_version:1,...(v==='add'?{command:'add'}:{}),result:'success',data})+'\\n');`);fs.chmodSync(ep,0o755);entrypoints[product]=ep}
 return{outer,input,logs,entrypoints,root:path.join(outer,"controlled-run"),config:{root:path.join(outer,"controlled-run"),outerRoot:outer,input,platform:"linux",arch:"amd64",expectedHead:HEAD,entrypoints,snapshotExcludes:[input,logs,...Object.values(entrypoints).map(x=>path.dirname(path.dirname(x)))]}}}
function dispose(f){fs.rmSync(f.outer,{recursive:true,force:true})}
test("consume executes ordered entrypoints in independent complete roots, compares JSON, proves revision/target, and cleans",()=>{const f=fixture();try{harness.consume(f.config);const receipt=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","run.json")));assert.equal(receipt.exact_candidate,true);assert.equal(receipt.cleanup,"complete");assert.equal(receipt.clean_root_separation,true);assert.equal(receipt.fixture_target_id,"codex");assert.ok(path.isAbsolute(receipt.fixture_roots.agentplugins));assert.equal(receipt.fixture_roots["plugin-kit-ai"],undefined);assert.equal(receipt.security_assessments["plugin-kit-ai"],undefined);assert.deepEqual(receipt.commands,harness.COMMANDS);assert.equal(receipt.package_acquisition.package_registry_or_latest_acquisition,false);assert.equal(receipt.package_acquisition.npm_tarball_install_offline,true);assert.ok(receipt.package_acquisition.exact_local_tarballs.every(x=>path.isAbsolute(x)&&x.endsWith(".tgz")));assert.equal(receipt.security_boundary.production_security_checks_enabled,true);assert.equal(receipt.security_boundary.credential_free_read_only_public_network_allowed,true);assert.equal(receipt.security_boundary.test_bypass,false);assert.equal(receipt.security_assessments.agentplugins.evidence_source,"local_scan");assert.equal(receipt.security_assessments.agentplugins.scanner.id,"lintai");
  for(const p of Object.keys(f.entrypoints)){const rows=fs.readFileSync(path.join(f.logs,p+".jsonl"),"utf8").trim().split("\n").map(JSON.parse);assert.deepEqual(rows.map(x=>x.argv[0]==="author"?x.argv[1]:x.argv[0]),p==="agentplugins"?["init","validate","inspect","test","add"]:["init","validate","inspect","test"]);assert.ok(Object.values(rows[0].env).every(x=>x.startsWith(path.join(f.root,"journeys",p))));assert.notEqual(rows[0].env.HOME,rows[0].env.TMPDIR);assert.notEqual(rows[0].env.npm_config_cache,rows[0].env.npm_config_prefix);}assert.deepEqual(fs.readdirSync(path.join(f.root,"journeys")),[]);}finally{dispose(f)}});
test("consume finds exact staged private-release provenance above the bin package scope",()=>{const f=fixture({stagedProvenance:true,resultRevision:null});try{harness.consume(f.config);const receipt=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","run.json")));for(const value of Object.values(receipt.provenances)){assert.equal(value.revision,HEAD);assert.equal(value.revision_field,"private-release.json#identity.commit");assert.equal(path.basename(value.package_manifest),"package.json");assert.equal(path.basename(path.dirname(value.package_manifest)).startsWith("package-"),true);}}finally{dispose(f)}});
test("portable precreation keeps an uploadable evidence path and Unix private modes",()=>{const outer=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-portable-root-")),root=path.join(outer,"run");try{fs.rmSync(outer,{recursive:true,force:true});assert.equal(harness.precreate(root,"win32"),path.join(root,"evidence"));assert.equal(fs.existsSync(path.join(root,"evidence")),true);fs.rmSync(outer,{recursive:true,force:true});harness.precreate(root,"linux");assert.equal(fs.statSync(root).mode&0o777,0o700);assert.equal(fs.statSync(path.join(root,"evidence")).mode&0o777,0o700);}finally{fs.rmSync(outer,{recursive:true,force:true})}});
test("init destination stays absent while the agentplugins launcher cache exists at journey/cache/candidate",()=>{const f=fixture({requireCandidateCache:true,requireDestinationAbsent:true});try{harness.consume(f.config);assert.deepEqual(fs.readdirSync(path.join(f.root,"journeys")),[]);}finally{dispose(f)}});
test("both public product journeys require and receive their own isolated private npm cache root before the launcher runs",()=>{const f=fixture({requireCandidateCache:true});try{harness.consume(f.config);const rows=Object.fromEntries(Object.keys(f.entrypoints).map(p=>[p,fs.readFileSync(path.join(f.logs,p+".jsonl"),"utf8").trim().split("\n").map(JSON.parse)]));assert.ok(rows.agentplugins.length>0);assert.ok(rows["plugin-kit-ai"].length>0);}finally{dispose(f)}});
test("local add dry-run reads the real single-target group/batch envelope, not a bare result, and is never sent to plugin-kit-ai",()=>{const f=fixture();try{const receipt=harness.consume(f.config);assert.equal(receipt.fixture_target_id,"codex");const agentpluginsRows=fs.readFileSync(path.join(f.logs,"agentplugins.jsonl"),"utf8").trim().split("\n").map(JSON.parse),pluginKitRows=fs.readFileSync(path.join(f.logs,"plugin-kit-ai.jsonl"),"utf8").trim().split("\n").map(JSON.parse);assert.ok(agentpluginsRows.map(x=>x.argv).some(a=>(a[0]==="author"?a[1]:a[0])==="add"));assert.ok(!pluginKitRows.map(x=>x.argv).some(a=>(a[0]==="author"?a[1]:a[0])==="add"));const security=receipt.security_assessments.agentplugins;assert.equal(security.scanner.id,"lintai");assert.equal(security.subject.tree_digest,D);assert.equal(security.subject.manifest_digest,R);assert.equal(receipt.security_assessments["plugin-kit-ai"],undefined);}finally{dispose(f)}});
test("darwin platform reads validate through a bounded hdiutil-mounted immutable local view and always detaches it",()=>{const stubDir=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-hdiutil-")),log=path.join(stubDir,"hdiutil.log"),bin=path.join(stubDir,"hdiutil");fs.writeFileSync(bin,`#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),a=process.argv.slice(2);
fs.appendFileSync(${JSON.stringify(log)},a.join(' ')+'\\n');
function copy(src,dst){fs.mkdirSync(dst,{recursive:true});for(const e of fs.readdirSync(src,{withFileTypes:true})){const s=path.join(src,e.name),d=path.join(dst,e.name);if(e.isDirectory())copy(s,d);else fs.copyFileSync(s,d)}}
if(a[0]==='create'){fs.writeFileSync(a[a.length-1],a[a.indexOf('-srcfolder')+1]);process.exit(0)}
if(a[0]==='attach'){copy(fs.readFileSync(a[a.length-1],'utf8'),a[a.indexOf('-mountpoint')+1]);process.exit(0)}
if(a[0]==='detach')process.exit(0);
process.exit(1);
`);fs.chmodSync(bin,0o755);const oldPath=process.env.PATH;process.env.PATH=`${stubDir}${path.delimiter}${oldPath}`;const f=fixture();f.config.platform="darwin";f.config.arch="arm64";try{const receipt=harness.consume(f.config);assert.equal(receipt.platform,"darwin");assert.deepEqual(receipt.commands,["init","validate"]);for(const p of Object.keys(f.entrypoints))assert.ok(receipt.assertions.includes(`${p}:packageview-readonly`));const lines=fs.readFileSync(log,"utf8").trim().split("\n");assert.equal(lines.filter(l=>l.startsWith("create ")).length,2);assert.equal(lines.filter(l=>l.startsWith("attach ")).length,2);assert.equal(lines.filter(l=>l.startsWith("detach ")).length,2);assert.equal(fs.readdirSync(path.join(f.root,"journeys")).length,0);}finally{process.env.PATH=oldPath;dispose(f);fs.rmSync(stubDir,{recursive:true,force:true})}});
test("darwin packageview mount is detached and journeys are cleaned even when the mounted validate fails",()=>{const stubDir=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-hdiutil-fail-")),log=path.join(stubDir,"hdiutil.log"),bin=path.join(stubDir,"hdiutil");fs.writeFileSync(bin,`#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),a=process.argv.slice(2);
fs.appendFileSync(${JSON.stringify(log)},a.join(' ')+'\\n');
function copy(src,dst){fs.mkdirSync(dst,{recursive:true});for(const e of fs.readdirSync(src,{withFileTypes:true})){const s=path.join(src,e.name),d=path.join(dst,e.name);if(e.isDirectory())copy(s,d);else fs.copyFileSync(s,d)}}
if(a[0]==='create'){fs.writeFileSync(a[a.length-1],a[a.indexOf('-srcfolder')+1]);process.exit(0)}
if(a[0]==='attach'){copy(fs.readFileSync(a[a.length-1],'utf8'),a[a.indexOf('-mountpoint')+1]);process.exit(0)}
if(a[0]==='detach')process.exit(0);
process.exit(1);
`);fs.chmodSync(bin,0o755);const oldPath=process.env.PATH;process.env.PATH=`${stubDir}${path.delimiter}${oldPath}`;const f=fixture({failValidate:true});f.config.platform="darwin";f.config.arch="arm64";try{assert.throws(()=>harness.consume(f.config),/exited 29/);const lines=fs.readFileSync(log,"utf8").trim().split("\n");assert.equal(lines.filter(l=>l.startsWith("attach ")).length,1);assert.equal(lines.filter(l=>l.startsWith("detach ")).length,1);assert.deepEqual(fs.readdirSync(path.join(f.root,"journeys")),[]);const failure=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","failure.json")));assert.equal(failure.cleanup,"complete");}finally{process.env.PATH=oldPath;dispose(f);fs.rmSync(stubDir,{recursive:true,force:true})}});
test("a darwin detach failure combined with a pre-existing primary error is fully visible in the thrown error and in evidence",()=>{const stubDir=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-hdiutil-detach-combined-")),log=path.join(stubDir,"hdiutil.log"),bin=path.join(stubDir,"hdiutil");fs.writeFileSync(bin,`#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),a=process.argv.slice(2);
fs.appendFileSync(${JSON.stringify(log)},a.join(' ')+'\\n');
function copy(src,dst){fs.mkdirSync(dst,{recursive:true});for(const e of fs.readdirSync(src,{withFileTypes:true})){const s=path.join(src,e.name),d=path.join(dst,e.name);if(e.isDirectory())copy(s,d);else fs.copyFileSync(s,d)}}
if(a[0]==='create'){fs.writeFileSync(a[a.length-1],a[a.indexOf('-srcfolder')+1]);process.exit(0)}
if(a[0]==='attach'){copy(fs.readFileSync(a[a.length-1],'utf8'),a[a.indexOf('-mountpoint')+1]);process.exit(0)}
if(a[0]==='detach')process.exit(1);
process.exit(1);
`);fs.chmodSync(bin,0o755);const oldPath=process.env.PATH;process.env.PATH=`${stubDir}${path.delimiter}${oldPath}`;const f=fixture({failValidate:true});f.config.platform="darwin";f.config.arch="arm64";try{assert.throws(()=>harness.consume(f.config),error=>/exited 29/.test(error.message)&&/darwin packageview detach failed for agentplugins/.test(error.message));assert.deepEqual(fs.readdirSync(path.join(f.root,"journeys")),[]);const failure=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","failure.json")));assert.match(failure.message,/exited 29/);assert.match(failure.message,/darwin packageview detach failed for agentplugins/);assert.equal(failure.cleanup,"complete");}finally{process.env.PATH=oldPath;dispose(f);fs.rmSync(stubDir,{recursive:true,force:true})}});
test("a darwin detach failure for one product does not prevent detach attempts, root cleanup, or the journey/outer-mutation checks for the other product",()=>{const stubDir=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-hdiutil-detach-partial-")),log=path.join(stubDir,"hdiutil.log"),bin=path.join(stubDir,"hdiutil");fs.writeFileSync(bin,`#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),a=process.argv.slice(2);
fs.appendFileSync(${JSON.stringify(log)},a.join(' ')+'\\n');
function copy(src,dst){fs.mkdirSync(dst,{recursive:true});for(const e of fs.readdirSync(src,{withFileTypes:true})){const s=path.join(src,e.name),d=path.join(dst,e.name);if(e.isDirectory())copy(s,d);else fs.copyFileSync(s,d)}}
if(a[0]==='create'){fs.writeFileSync(a[a.length-1],a[a.indexOf('-srcfolder')+1]);process.exit(0)}
if(a[0]==='attach'){copy(fs.readFileSync(a[a.length-1],'utf8'),a[a.indexOf('-mountpoint')+1]);process.exit(0)}
if(a[0]==='detach'){if(a[a.length-1].includes('plugin-kit-ai'))process.exit(1);process.exit(0)}
process.exit(1);
`);fs.chmodSync(bin,0o755);const oldPath=process.env.PATH;process.env.PATH=`${stubDir}${path.delimiter}${oldPath}`;const f=fixture();f.config.platform="darwin";f.config.arch="arm64";try{assert.throws(()=>harness.consume(f.config),/darwin packageview detach failed for plugin-kit-ai/);const lines=fs.readFileSync(log,"utf8").trim().split("\n");assert.equal(lines.filter(l=>l.startsWith("attach ")).length,2);assert.equal(lines.filter(l=>l.startsWith("detach ")).length,2);assert.deepEqual(fs.readdirSync(path.join(f.root,"journeys")),[]);for(const p of Object.keys(f.entrypoints)){const rows=fs.readFileSync(path.join(f.logs,p+".jsonl"),"utf8").trim().split("\n").map(JSON.parse);assert.deepEqual(rows.map(x=>x.argv[0]==="author"?x.argv[1]:x.argv[0]),["init","validate"]);}const failure=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","failure.json")));assert.match(failure.message,/darwin packageview detach failed for plugin-kit-ai/);assert.equal(failure.cleanup,"complete");assert.equal(failure.clean_root_separation,true);}finally{process.env.PATH=oldPath;dispose(f);fs.rmSync(stubDir,{recursive:true,force:true})}});
test("failed real commands retain complete stdout and stderr in evidence",()=>{const f=fixture({failAdd:true});try{assert.throws(()=>harness.consume(f.config),error=>error.message.includes("exited 23")&&error.message.includes("stdout:\ncomplete stdout diagnostic")&&error.message.includes("stderr:\ncomplete stderr diagnostic"));const failure=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","failure.json")));assert.match(failure.message,/stdout:\ncomplete stdout diagnostic\nstderr:\ncomplete stderr diagnostic/);}finally{dispose(f)}});
test("journey environment preserves public HTTPS transport without leaking unrelated host state",()=>{const f=fixture();const old={HTTPS_PROXY:process.env.HTTPS_PROXY,SSL_CERT_FILE:process.env.SSL_CERT_FILE,UNRELATED_MILESTONE_SECRET:process.env.UNRELATED_MILESTONE_SECRET};try{process.env.HTTPS_PROXY="http://proxy.invalid:8443";process.env.SSL_CERT_FILE="/etc/ssl/cert.pem";process.env.UNRELATED_MILESTONE_SECRET="must-not-pass";const j={home:path.join(f.outer,"home"),tmp:path.join(f.outer,"tmp"),config:path.join(f.outer,"config"),cache:path.join(f.outer,"cache"),data:path.join(f.outer,"data"),state:path.join(f.outer,"state"),appdata:path.join(f.outer,"appdata"),localappdata:path.join(f.outer,"localappdata"),client:path.join(f.outer,"client"),npm_cache:path.join(f.outer,"npm-cache"),npm_prefix:path.join(f.outer,"npm-prefix")},env=harness.envFor(j);assert.equal(env.HTTPS_PROXY,process.env.HTTPS_PROXY);assert.equal(env.SSL_CERT_FILE,process.env.SSL_CERT_FILE);assert.equal(env.UNRELATED_MILESTONE_SECRET,undefined);assert.equal(env.npm_config_offline,"true");}finally{for(const [key,value] of Object.entries(old))if(value===undefined)delete process.env[key];else process.env[key]=value;dispose(f)}});
test("trusted npm CLI is a JavaScript entrypoint invoked by node with explicit arguments",()=>{const npmCLI=harness.resolveNpmCLI();assert.equal(path.extname(npmCLI),".js");const source=fs.readFileSync(path.join(repo,"npm/agentplugins/scripts/milestone-a-e2e.js"),"utf8");assert.match(source,/run\(process\.execPath,\[npmCLI,"install"/);assert.doesNotMatch(source,/spawnSync\([^\n]*(?:npm\.cmd|shell:\s*true)/);});
test("local add dry-run source argv is an explicit absolute local path, not a bare dot",()=>{const source=fs.readFileSync(path.join(repo,"npm/agentplugins/scripts/milestone-a-e2e.js"),"utf8");assert.match(source,/\[ep,"add",j\.project,"--target=codex","--dry-run","--format=json"\]/);assert.doesNotMatch(source,/\[ep,"add","\."/);});
test("Windows mixed-separator runner roots become canonical native absolute paths",()=>{assert.equal(harness.nativeAbsolute("D:\\a\\_temp/milestone-a/run","win32"),"D:\\a\\_temp\\milestone-a\\run");assert.equal(path.win32.isAbsolute(harness.nativeAbsolute("D:\\a\\_temp/milestone-a/run","win32")),true);assert.throws(()=>harness.nativeAbsolute("milestone-a/run","win32"),/root must be absolute/);});
for(const [name,opts,pattern] of [
 ["normalized result mismatch",{mismatch:true},/command JSON differs/],
 ["reported candidate revision mismatch",{resultRevision:"1111111111111111111111111111111111111111"},/reported revision/],
 ["package provenance revision mismatch",{resultRevision:null,packageRevision:"2222222222222222222222222222222222222222"},/package provenance revision/],
 ["reported outside-root path",{outside:true},/escapes journey root/]
])test(`negative executable: ${name} writes failure evidence and cleans`,()=>{const f=fixture(opts);try{assert.throws(()=>harness.consume(f.config),pattern);const failure=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","failure.json")));assert.match(failure.message,pattern);assert.equal(failure.cleanup,"complete");assert.deepEqual(fs.readdirSync(path.join(f.root,"journeys")),[]);}finally{dispose(f)}});
for(const [name,opts,pattern] of [["absent security",{noSecurity:true},/omitted authoritative production security evidence/],["failed security",{failedSecurity:true},/security assessment did not pass/],["wrong target ID",{wrongTarget:true},/resolve target exactly to codex/],["wrong requested target",{wrongRequestedTarget:true},/resolve target exactly to codex/],["contained non-Codex destination",{destination:"<JOURNEY>/state/planned"},/planned destination escapes journey root/],["escaped destination",{destination:path.resolve(os.tmpdir(),"milestone-a-escape")},/planned destination escapes journey root/]])test(`negative add evidence: ${name}`,()=>{const f=fixture(opts);try{assert.throws(()=>harness.consume(f.config),pattern);const failure=JSON.parse(fs.readFileSync(path.join(f.root,"evidence","failure.json")));assert.match(failure.message,pattern);assert.equal(failure.cleanup,"complete");}finally{dispose(f)}});
test("outside sibling mutation is rejected",()=>{const f=fixture();const marker=path.join(f.outer,"unexpected-sibling");fs.appendFileSync(f.entrypoints.agentplugins,`\nfs.writeFileSync(${JSON.stringify(marker)},'changed');\n`);try{assert.throws(()=>harness.consume(f.config),/unexpected change outside/);}finally{dispose(f)}});
test("tree and snapshot reject links",()=>{const r=fs.mkdtempSync(path.join(os.tmpdir(),"milestone-a-link-"));try{fs.writeFileSync(path.join(r,"a"),"a");fs.symlinkSync(path.join(r,"a"),path.join(r,"link"));assert.throws(()=>harness.tree(r),/non-regular/);assert.throws(()=>harness.snapshot(r),/link/);}finally{fs.rmSync(r,{recursive:true,force:true});}});
test("Windows normalization is root-specific, case-aware, and separator-aware",()=>{const a={data:{product:"agentplugins",product_version:"2",help:{use:"agentplugins author validate"},project:"C:\\RUNS\\Alpha\\project",nested:["C:/runs/alpha/project/plugin.json","C:\\runs\\unrelated\\project"]}},b={data:{product:"plugin-kit-ai",product_version:"2",help:{use:"plugin-kit-ai validate"},project:"D:\\work\\Beta\\project",nested:["D:/WORK/beta/project/plugin.json","C:\\runs\\unrelated\\project"]}};const na=harness.normalize(a,"C:\\runs\\alpha\\project","win32"),nb=harness.normalize(b,"D:\\work\\beta\\project","win32");assert.equal(na.data.project,"<journey>/project");assert.equal(na.data.nested[0],"<journey>/project/plugin.json");assert.deepEqual(na,nb);});
test("negative Windows normalization preserves unrelated paths, similar roots, and escapes",()=>{const value={data:{outside:"C:\\elsewhere\\file",escape:"C:\\root\\one\\..\\secret",similar:"C:\\root\\one-other\\file"}};assert.deepEqual(harness.normalize(value,"C:\\root\\one\\project","win32"),value);});
test("workflow uses real local packages and has no test entrypoint injection",()=>{assert.match(workflow,/download-artifact@[0-9a-f]{40}[\s\S]*milestone-a-input/);assert.match(workflow,/milestone-a-e2e\.js run/);assert.match(workflow,/production security checks retain credential-free read-only access/);assert.doesNotMatch(workflow,/JSON\.stringify\(\{[^}]*entrypoints|fixture|fake|test[_-]only|registry_fallback|complete installer journey is offline/i);const source=fs.readFileSync(path.join(repo,"npm/agentplugins/scripts/milestone-a-e2e.js"),"utf8");for(const token of ['[npmCLI,"install","--ignore-scripts","--offline"','path.join(input,"packages",tgz)','path.join(j.installation,"node_modules"'])assert.ok(source.includes(token),`missing real-package contract: ${token}`);});
test("workflow is unfiltered, secretless, pinned, bounded and failure-preserving",()=>{assert.match(workflow,/pull_request:\s*\n\s*workflow_dispatch:/);assert.doesNotMatch(workflow,/pull_request:[\s\S]{0,200}paths:/);assert.match(workflow,/permissions:\n  contents: read/);assert.doesNotMatch(workflow,/secrets\.|permissions:\s*write|publish|npm-token|id-token/);assert.match(workflow,/ubuntu-24\.04[\s\S]*windows-2022[\s\S]*macos-14/);assert.match(workflow,/if: always\(\)[\s\S]*actions\/upload-artifact@[0-9a-f]{40}/);assert.doesNotMatch(workflow,/uses:\s*[^\n]+@(?![0-9a-f]{40}(?:\s|$))/);for(const n of [...workflow.matchAll(/timeout-minutes:\s*(\d+)/g)].map(x=>+x[1]))assert.ok(n<=20);assert.match(workflow,/NODE_OPTIONS: --max-old-space-size=384/);});
test("workflow creates a private prepare upload root before packing and installs a bounded failure receipt",()=>{assert.match(workflow,/test ! -e "\$root"\s+mkdir -m 700 "\$root"\s+mkdir -m 700 "\$root\/evidence"/);assert.match(workflow,/precreatedRoot:true/);assert.match(workflow,/milestone-a-e2e-workflow-failure\/v1/);assert.match(workflow,/\.slice\(0,4096\)|status:Number/);});
test("workflow precreates portable run evidence before execution and uploads that stable path",()=>{const run=workflow.slice(workflow.indexOf("Run both packaged public entrypoints"));assert.match(run,/native_root=.*nativeAbsolute[\s\S]*MILESTONE_A_EVIDENCE=%s[\s\S]*\.precreate\(process\.argv\[1\]\)/);assert.match(run,/native_outer=.*nativeAbsolute[\s\S]*native_input=.*nativeAbsolute/);assert.match(run,/precreatedRoot:true/);assert.doesNotMatch(run,/mkdir -m 700|rmdir \"\$root\/evidence\"/);assert.match(run,/if: always\(\)[\s\S]*path: \$\{\{ env\.MILESTONE_A_EVIDENCE \}\}/);});
test("workflow converts the MSYS run config path to native Win32 before writing and invoking",()=>{const run=workflow.slice(workflow.indexOf("Run both packaged public entrypoints"));assert.match(run,/native_config=.*nativeAbsolute\(process\.argv\[1\]\)[\s\S]*writeFileSync\(process\.argv\[1\][\s\S]*\"\$native_config\"[\s\S]*milestone-a-e2e\.js run \"\$native_config\"/);assert.doesNotMatch(run,/milestone-a-e2e\.js run \"\$config\"/);});
test("workflow gives Darwin packageview a local read-only APFS candidate and always detaches it",()=>{assert.match(workflow,/runner\.os == 'macOS'[\s\S]*hdiutil create[^\n]*-fs APFS -format UDRO[\s\S]*hdiutil attach[^\n]*-readonly/);assert.match(workflow,/candidateRoot:process\.argv\[5\]/);assert.match(workflow,/if: always\(\) && runner\.os == 'macOS'[\s\S]*hdiutil detach/);});
test("workflow canonicalizes trusted prepare tools before constructing config",()=>{assert.match(workflow,/resolveTrustedTools\(process\.argv\[3\],process\.argv\[5\]\)/);assert.doesNotMatch(workflow,/npm:process\.argv\[5\]/);});
}
