package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func rendered(t *testing.T) (map[string][]byte, manifest) {
	t.Helper()
	roots, err := trees()
	if err != nil {
		t.Fatal(err)
	}
	// Every executable hook is a trap: generation must only inspect definitions.
	var trap func(*cobra.Command)
	trap = func(c *cobra.Command) {
		c.Run = func(*cobra.Command, []string) { t.Fatal("Run called") }
		c.RunE = func(*cobra.Command, []string) error { t.Fatal("RunE called"); return nil }
		c.Args = func(*cobra.Command, []string) error { t.Fatal("Args called"); return nil }
		c.PreRunE = c.RunE
		c.PersistentPreRunE = c.RunE
		c.PostRunE = c.RunE
		c.PersistentPostRunE = c.RunE
		c.ValidArgsFunction = func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			t.Fatal("completion called")
			return nil, 0
		}
		for _, ch := range c.Commands() {
			trap(ch)
		}
	}
	for _, root := range roots {
		trap(root)
	}
	files, err := render(preparedSourceSHA, factoryPins, roots)
	if err != nil {
		t.Fatal(err)
	}
	var m manifest
	if err := json.Unmarshal(files[namespace+"/manifest.json"], &m); err != nil {
		t.Fatal(err)
	}
	return files, m
}

func TestDeterministicSurfacesAndNoActions(t *testing.T) {
	sandbox := t.TempDir()
	t.Setenv("HOME", sandbox)
	t.Setenv("USERPROFILE", sandbox)
	t.Setenv("TMPDIR", sandbox)
	first, m := rendered(t)
	second, _ := rendered(t)
	if !reflect.DeepEqual(first, second) {
		t.Fatal("fresh exports differ")
	}
	if m.Released || m.Status != "prepared-not-release" || m.SourceSHA != preparedSourceSHA || m.Namespace != namespace {
		t.Fatal("identity")
	}
	if len(m.Surfaces) != 2 || m.Surfaces[0].CommandPath != "plugin-kit-ai" || m.Surfaces[1].CommandPath != "agentplugins author" {
		t.Fatal("surfaces")
	}
	authorNames := []string{"", "capabilities", "compat", "doctor", "init", "inspect", "skills", "skills init", "skills validate", "help", "skills help", "test", "validate", "version"}
	for i, s := range m.Surfaces {
		want := map[string]bool{}
		for _, n := range authorNames {
			want[strings.TrimSpace(s.CommandPath+" "+n)] = true
		}
		if i == 0 {
			for _, n := range []string{"completion", "completion bash", "completion fish", "completion help", "completion powershell", "completion zsh"} {
				want[s.CommandPath+" "+n] = true
			}
		}
		for _, e := range s.Commands {
			if !want[e.CommandPath] {
				t.Fatalf("unexpected command %s", e.CommandPath)
			}
			delete(want, e.CommandPath)
			body, ok := first[e.FileName]
			if !ok || !bytes.Contains(body, []byte(e.Short)) {
				t.Fatalf("missing Markdown/help %s", e.CommandPath)
			}
			if !strings.HasPrefix(e.Identity, namespace+":") {
				t.Fatal("v1 identity reuse")
			}
		}
		if len(want) > 0 {
			t.Fatalf("missing commands: %v", want)
		}
	}
	for _, body := range first {
		for _, bad := range []string{"Auto generated by", sandbox, "__docs", "__complete", "plugin-kit-ai generate", "skills install"} {
			if bytes.Contains(body, []byte(bad)) {
				t.Fatalf("unwanted output %q", bad)
			}
		}
	}
	entries, err := os.ReadDir(sandbox)
	if err != nil || len(entries) != 0 {
		t.Fatalf("generation mutated sandbox: %v %v", entries, err)
	}
}

func TestFlagFidelity(t *testing.T) {
	files, m := rendered(t)
	for _, s := range m.Surfaces {
		var init entry
		for _, e := range s.Commands {
			if e.CommandPath == s.CommandPath+" init" {
				init = e
			}
		}
		local := map[string]flagFact{}
		inherited := map[string]flagFact{}
		for _, f := range init.LocalFlags {
			local[f.Name] = f
		}
		for _, f := range init.InheritedFlags {
			inherited[f.Name] = f
		}
		if init.Use != "init <path>" || local["mcp-template"].Usage != "hybrid MCP choice: mcp-remote or mcp-stdio" || local["runtime"].Usage != "stdio template runtime: node" {
			t.Fatal("local facts lost")
		}
		for _, bad := range []string{"mcp", "platform", "strict", "force", "output"} {
			if _, ok := local[bad]; ok {
				t.Fatal("retired flag", bad)
			}
		}
		if inherited["format"].Default != "human" || inherited["no-color"].Type != "bool" || inherited["no-color"].NoOptDefault != "true" {
			t.Fatal("inherited facts lost")
		}
		if s.CommandPath == "agentplugins author" {
			if inherited["scope"].Default != "user" || inherited["accept-security-risk"].Type != "bool" || !strings.Contains(init.Long, "are rejected") {
				t.Fatal("installer inheritance lost")
			}
		} else if _, ok := inherited["scope"]; ok {
			t.Fatal("installer flags leaked")
		}
		for _, f := range append(init.LocalFlags, init.InheritedFlags...) {
			if !bytes.Contains(files[init.FileName], []byte("--"+f.Name)) {
				t.Fatalf("Markdown omitted flag %s", f.Name)
			}
		}
	}
}

func TestExclusionPrunesLinksAndDescendants(t *testing.T) {
	root := &cobra.Command{Use: "probe"}
	for _, c := range []*cobra.Command{
		{Use: "hidden", Hidden: true},
		{Use: "shim", Annotations: map[string]string{"authoringcli.v1-rejection": "v1"}},
		{Use: "__internal"},
	} {
		c.AddCommand(&cobra.Command{Use: "visible-child", Run: func(*cobra.Command, []string) { t.Fatal("executed") }})
		root.AddCommand(c)
	}
	root.Flags().String("secret", "", "hidden flag")
	_ = root.Flags().MarkHidden("secret")
	files, err := render(preparedSourceSHA, nil, []*cobra.Command{root})
	if err != nil {
		t.Fatal(err)
	}
	for _, body := range files {
		for _, bad := range []string{"visible-child", "shim", "__internal", "secret"} {
			if bytes.Contains(body, []byte(bad)) {
				t.Fatal("exclusion leaked", bad)
			}
		}
	}
}

func TestSourceIdentityAndNoOverwrite(t *testing.T) {
	checkout, err := filepath.Abs("../../../..")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := validateSource(checkout, preparedSourceSHA); err != nil {
		t.Fatal(err)
	}
	for _, sha := range []string{"", "070663e", strings.Repeat("0", 40), preparedSourceSHA + "\n"} {
		dest := filepath.Join(t.TempDir(), "output")
		if err := export(checkout, sha, dest); err == nil {
			t.Fatal("accepted bad source", sha)
		}
		if _, err := os.Stat(dest); !os.IsNotExist(err) {
			t.Fatal("wrote output for bad source")
		}
	}
	dest := t.TempDir()
	marker := filepath.Join(dest, "v1.md")
	if err := os.WriteFile(marker, []byte("keep v1"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := export(checkout, preparedSourceSHA, dest); err == nil {
		t.Fatal("accepted existing output")
	}
	body, _ := os.ReadFile(marker)
	if string(body) != "keep v1" {
		t.Fatal("overwrote v1")
	}
	if _, err := validateSource(t.TempDir(), preparedSourceSHA); err == nil {
		t.Fatal("accepted non-checkout")
	}
}

func TestExportBytesAndLinks(t *testing.T) {
	checkout, err := filepath.Abs("../../../..")
	if err != nil {
		t.Fatal(err)
	}
	base := t.TempDir()
	a, b := filepath.Join(base, "a"), filepath.Join(base, "b")
	for _, dest := range []string{a, b} {
		if err := export(checkout, preparedSourceSHA, dest); err != nil {
			t.Fatal(err)
		}
	}
	err = filepath.WalkDir(a, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(a, path)
		first, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		second, err := os.ReadFile(filepath.Join(b, rel))
		if err != nil {
			return err
		}
		if !bytes.Equal(first, second) {
			t.Fatalf("nondeterministic file %s", rel)
		}
		if strings.HasSuffix(path, ".md") {
			for _, line := range strings.Split(string(first), "\n") {
				if !strings.HasPrefix(line, "* [") {
					continue
				}
				parts := strings.SplitN(line, "](", 2)
				if len(parts) != 2 {
					continue
				}
				target := strings.SplitN(parts[1], ")", 2)[0]
				if strings.HasPrefix(target, "https://github.com/777genius/universal-agent-plugins/blob/"+preparedSourceSHA+"/") {
					continue
				}
				if _, err := os.Stat(filepath.Join(filepath.Dir(path), target)); err != nil {
					t.Fatalf("broken generated link %s -> %s", rel, target)
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCheckoutHEADMismatch(t *testing.T) {
	// Minimal disposable Git metadata; no commit, checkout, or real profile edits.
	checkout := t.TempDir()
	for _, name := range []string{".git/objects", ".git/refs"} {
		if err := os.MkdirAll(filepath.Join(checkout, name), 0700); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(checkout, ".git/HEAD"), []byte(strings.Repeat("1", 40)+"\n"), 0600); err != nil {
		t.Fatal(err)
	}
	_, err := validateSource(checkout, preparedSourceSHA)
	if err == nil || !strings.Contains(err.Error(), "differs from checkout HEAD") {
		t.Fatalf("wrong mismatch result: %v", err)
	}
}
