package scaffold

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"unicode"
	"unicode/utf8"
)

// SkillPlan can contain only one generated immediate-child Skill. It is not an
// arbitrary Plan constructor: neither paths, modes nor file contents are inputs.
type SkillPlan struct {
	name string
	body []byte
}

func BuildSkillPlan(ctx context.Context, name, description string) (SkillPlan, error) {
	if ctx == nil {
		return SkillPlan{}, errors.New("context required")
	}
	if len(name) > 256 || len(description) > 4096 || !utf8.ValidString(description) {
		return SkillPlan{}, errors.New("skill input exceeds text bounds")
	}
	n, _ := json.Marshal(name)
	d, _ := json.Marshal(description)
	p := SkillPlan{name, []byte("---\nname: " + string(n) + "\ndescription: " + string(d) + "\n---\n\n# " + name + "\n\n" + description + "\n")}
	if err := ctx.Err(); err != nil {
		return SkillPlan{}, err
	}
	if err := skillOutputName(name); err != nil {
		return SkillPlan{}, err
	}
	if !textValue(description, 1024) {
		return SkillPlan{}, errors.New("explicit bounded description required")
	}
	return p, nil
}

// File returns a reviewable deep copy, never mutable access to the plan.
func (p SkillPlan) File() File {
	return File{Path: "skills/" + p.name + "/SKILL.md", Bytes: append([]byte(nil), p.body...), Mode: 0644}
}

// This is host path safety only. Semantic name/frontmatter policy belongs to
// the mandatory shared-profile validator supplied by the Skills service.
func skillOutputName(name string) error {
	if len(name) > 256 || !utf8.ValidString(name) || !fs.ValidPath(name) || name == "." || strings.ContainsAny(name, `/\\:*?"<>|`) || strings.HasSuffix(name, ".") || strings.HasSuffix(name, " ") {
		return errors.New("unsafe skill output name")
	}
	ascii := true
	for _, r := range name {
		if unicode.IsControl(r) {
			return errors.New("unsafe skill output name")
		}
		if r > 127 {
			ascii = false
		}
	}
	if ascii {
		return portableLeaf(name)
	}
	return nil
}

// SkillValidation must decode these actual bounded generated bytes through the
// shared normative profile. A success stub violates the same trusted-composition
// contract as Apply.Validate. Nil is rejected before filesystem access.
type SkillValidation func(context.Context, []byte) error

// SkillSourceGate must read the exact source with the shared bounded project
// service, require a valid core and host containment, and return a bounded
// recheck of the captured core. It runs before staging, while roots are held.
// Rechecks must retain the reader's nonblocking/metadata-only alias protections.
// Like Apply's Validate port, this is trusted in-process composition, not a
// user-supplied authorization mechanism. A success stub violates the contract.
type SkillSourceGate func(context.Context, string) (func(context.Context) error, error)

// ApplySkill reuses scaffold's private staging, bounded writer, exact-tree
// verification, owned cleanup and exclusive rename primitives. The package
// transaction cannot be reused directly: it requires root plugin.json and an
// absent package destination. This bounded seam changes only skills/<name>.
// When skills is absent, publish the entire new skills directory in one rename;
// a concurrent creator wins or loses that same no-replace operation cleanly.
func ApplySkill(ctx context.Context, p SkillPlan, exactRoot string, gate SkillSourceGate, validate SkillValidation) (Result, error) {
	return applySkill(ctx, p, exactRoot, gate, validate, applyOps{write: writeTree, rename: renameExclusive})
}

func applySkill(ctx context.Context, p SkillPlan, exactRoot string, gate SkillSourceGate, validate SkillValidation, ops applyOps) (result Result, err error) {
	if ctx == nil || gate == nil || validate == nil {
		return result, errors.New("context, source gate and shared profile validator required")
	}
	if err = ctx.Err(); err != nil {
		return
	}
	if len(p.body) == 0 || len(p.body) > maxBytes || skillOutputName(p.name) != nil {
		return result, errors.New("invalid skill plan")
	}
	switch runtime.GOOS {
	case "linux", "darwin", "windows":
	default:
		return result, errors.New("exclusive skill publication unsupported")
	}
	if !filepath.IsAbs(exactRoot) || filepath.Clean(exactRoot) != exactRoot || len(exactRoot) > 4096 {
		return result, errors.New("package root must be clean and absolute")
	}
	source, e := openParent(exactRoot)
	if e != nil {
		return result, e
	}
	defer func() { err = errors.Join(err, source.Close()) }()
	sourceInfo, e := source.Stat(".")
	if e != nil {
		return result, e
	}
	parent, parentPath, destination := source, exactRoot, "skills"
	files := []File{{Path: p.name + "/SKILL.md", Bytes: p.body, Mode: 0644}}
	info, e := source.Lstat("skills")
	if e == nil {
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return result, errors.New("skills parent must be a real directory")
		}
		parent, e = source.OpenRoot("skills")
		if e != nil {
			return result, e
		}
		defer func() { err = errors.Join(err, parent.Close()) }()
		now, e := parent.Stat(".")
		if e != nil || !os.SameFile(info, now) {
			return result, errors.New("skills parent changed")
		}
		parentPath, destination = filepath.Join(exactRoot, "skills"), p.name
		files[0].Path = "SKILL.md"
	} else if !errors.Is(e, os.ErrNotExist) {
		return result, e
	}
	parentInfo, e := parent.Stat(".")
	if e != nil {
		return result, e
	}
	if e = skillAbsent(parent, destination); e != nil {
		return result, e
	}
	// A competing writer's reservation is already a collision, even before
	// publication. Reject it by metadata before the source gate tries to capture
	// that writer's open reservation/private stage (unreadable on Windows).
	// This check grants no write authority; the exclusive reservation is still
	// acquired only after the full source gate and precondition below.
	reservation := skillReservation(p.name)
	if e = absent(source, reservation); e != nil {
		return result, e
	}
	recheck, e := gate(ctx, exactRoot)
	if e != nil {
		return result, e
	}
	if recheck == nil {
		return result, errors.New("source core evidence required")
	}
	precondition := func() error {
		if e := ctx.Err(); e != nil {
			return e
		}
		if e := checkParent(exactRoot, sourceInfo); e != nil {
			return e
		}
		if e := checkParent(parentPath, parentInfo); e != nil {
			return e
		}
		if e := recheck(ctx); e != nil {
			return e
		}
		if e := checkParent(exactRoot, sourceInfo); e != nil {
			return e
		}
		if e := checkParent(parentPath, parentInfo); e != nil {
			return e
		}
		return skillAbsent(parent, destination)
	}
	if e = precondition(); e != nil {
		return result, e
	}
	// Reserve a Unicode case-fold identity across concurrent Skills writers.
	// The kernel still owns exact-destination absence at commit. Acquire only
	// after the source gate; never remove an existing or replaced reservation.
	reservationFile, e := source.OpenFile(reservation, os.O_CREATE|os.O_EXCL|os.O_RDWR, 0600)
	if e != nil {
		return result, e
	}
	reserved, e := reservationFile.Stat()
	if e != nil {
		return result, errors.Join(reservationFile.Close(), &CleanupError{e})
	}
	defer func() {
		closeErr := reservationFile.Close()
		now, e := source.Lstat(reservation)
		if e == nil && os.SameFile(reserved, now) {
			e = source.Remove(reservation)
		} else {
			e = errors.New("skill reservation ownership changed; replacement preserved")
		}
		e = errors.Join(e, closeErr)
		if e != nil {
			err = errors.Join(err, &CleanupError{e})
		}
	}()
	stage := ".authoring-" + rand.Text()
	if e = makePrivateStage(parent, stage); e != nil {
		return result, e
	}
	stageInfo, e := parent.Lstat(stage)
	if e != nil {
		return result, &CleanupError{e}
	}
	owned, e := parent.OpenRoot(stage)
	if e != nil {
		now, statErr := parent.Lstat(stage)
		if statErr == nil && os.SameFile(stageInfo, now) {
			return result, errors.Join(e, parent.Remove(stage))
		}
		return result, errors.Join(e, &CleanupError{errors.New("stage ownership unavailable")})
	}
	now, e := owned.Stat(".")
	if e != nil || !os.SameFile(stageInfo, now) {
		return result, errors.Join(errors.New("stage ownership changed"), owned.Close(), &CleanupError{errOr(e, fs.ErrInvalid)})
	}
	defer func() {
		cleanup := owned.Close()
		now, e := parent.Lstat(stage)
		if e == nil && os.SameFile(stageInfo, now) {
			cleanup = errors.Join(cleanup, parent.Remove(stage))
		} else {
			cleanup = errors.Join(cleanup, errors.New("stage ownership changed; replacement preserved"))
		}
		if cleanup != nil {
			err = errors.Join(err, &CleanupError{cleanup})
		}
	}()
	if e = owned.Mkdir("payload", 0700); e != nil {
		return result, e
	}
	payload, e := owned.OpenRoot("payload")
	if e != nil {
		return result, e
	}
	payloadInfo, e := payload.Stat(".")
	if e != nil {
		return result, errors.Join(e, payload.Close())
	}
	defer func() {
		var cleanup error
		if !result.Committed {
			cleanup = clearOwnedPayload(payload)
		}
		cleanup = errors.Join(cleanup, payload.Close())
		if !result.Committed {
			now, e := owned.Lstat("payload")
			if e == nil && os.SameFile(payloadInfo, now) {
				cleanup = errors.Join(cleanup, owned.Remove("payload"))
			} else {
				cleanup = errors.Join(cleanup, errors.New("payload ownership changed; replacement preserved"))
			}
		}
		if cleanup != nil {
			err = errors.Join(err, &CleanupError{cleanup})
		}
	}()
	if e = ops.write(ctx, payload, files); e != nil {
		return result, e
	}
	// Validate actual generated bytes through the shared bounded decoder, using
	// the pinned private payload. No synthetic success or separate YAML parser.
	body, e := skillReadRegular(payload, files[0].Path, maxBytes)
	if e != nil {
		return result, e
	}
	if e = validate(ctx, body); e != nil {
		return result, e
	}
	if e = verifyTree(ctx, payload, files); e != nil {
		return result, e
	}
	if e = precondition(); e != nil {
		return result, e
	}
	reservationNow, e := source.Lstat(reservation)
	if e != nil || !os.SameFile(reserved, reservationNow) {
		return result, errors.New("skill reservation ownership changed")
	}
	now, e = parent.Lstat(stage)
	if e != nil || !os.SameFile(stageInfo, now) {
		return result, errors.New("stage ownership changed")
	}
	now, e = owned.Lstat("payload")
	if e != nil || !now.IsDir() || now.Mode()&os.ModeSymlink != 0 || !os.SameFile(payloadInfo, now) {
		return result, errors.New("payload ownership changed")
	}
	from, e := owned.Open(".")
	if e != nil {
		return result, e
	}
	to, e := parent.Open(".")
	if e != nil {
		return result, errors.Join(e, from.Close())
	}
	e = ctx.Err()
	if e == nil {
		e = ops.rename(from, "payload", to, destination)
	}
	if e == nil {
		result = Result{Destination: filepath.Join(exactRoot, "skills", p.name), Committed: true}
	}
	return result, errors.Join(e, from.Close(), to.Close())
}

// A bounded metadata-only scan rejects case-fold aliases on every host. The
// kernel exclusive rename still decides an exact destination race.
func skillAbsent(r *os.Root, name string) error {
	if err := absent(r, name); err != nil {
		return err
	}
	dir, err := r.Open(".")
	if err != nil {
		return err
	}
	names, e := dir.Readdirnames(10001)
	if errors.Is(e, io.EOF) {
		e = nil
	}
	err = errors.Join(e, dir.Close())
	if err != nil {
		return err
	}
	if len(names) > 10000 {
		return errors.New("destination inventory exceeds bound")
	}
	for _, n := range names {
		if strings.EqualFold(n, name) {
			return os.ErrExist
		}
	}
	return nil
}

func skillReadRegular(r *os.Root, path string, limit int) ([]byte, error) {
	info, err := r.Lstat(path)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Size() > int64(limit) {
		return nil, errors.New("regular bounded file required")
	}
	f, err := r.Open(path)
	if err != nil {
		return nil, err
	}
	now, e := f.Stat()
	if e != nil || !os.SameFile(info, now) {
		return nil, errors.Join(errors.New("file changed while opening"), e, f.Close())
	}
	b, e := io.ReadAll(io.LimitReader(f, int64(limit)+1))
	e = errors.Join(e, f.Close())
	if e != nil {
		return nil, e
	}
	if len(b) > limit {
		return nil, errors.New("file exceeds bound")
	}
	return b, nil
}

// SimpleFold cycles define the same equivalence as strings.EqualFold. Hash the
// canonical cycle representatives so reservation paths contain no user text.
func skillReservation(name string) string {
	folded := []rune(name)
	for i, r := range folded {
		smallest := r
		for next := unicode.SimpleFold(r); next != r; next = unicode.SimpleFold(next) {
			if next < smallest {
				smallest = next
			}
		}
		folded[i] = smallest
	}
	digest := sha256.Sum256([]byte(string(folded)))
	return ".authoring-skill-" + hex.EncodeToString(digest[:])
}
