package pluginkitairepo_test

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestContractClarity_RuntimeMetadataAndDocsStayAligned(t *testing.T) {
	root := RepoRoot(t)
	pluginKitAIBin := buildPluginKitAI(t)
	goSDKVersion := repoGoSDKVersion(t)
	runtimePackageVersion := repoRuntimePackageVersion(t)

	matrixPath := filepath.Join(root, "docs", "generated", "support_matrix.md")
	matrixBody, err := os.ReadFile(matrixPath)
	if err != nil {
		t.Fatal(err)
	}
	matrix := string(matrixBody)
	mustContain(t, matrix, "| claude | Stop | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| claude | SessionStart | runtime_supported | beta | runtime-supported but not stable | false |")
	mustContain(t, matrix, "| gemini | SessionStart | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | SessionEnd | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | BeforeModel | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | AfterModel | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | BeforeToolSelection | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | BeforeAgent | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | AfterAgent | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | BeforeTool | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| gemini | AfterTool | runtime_supported | stable | production-ready | true |")
	mustContain(t, matrix, "| codex | Notify | runtime_supported | stable | production-ready | true |")
	targetMatrixBody, err := os.ReadFile(filepath.Join(root, "docs", "generated", "target_support_matrix.md"))
	if err != nil {
		t.Fatal(err)
	}
	targetMatrix := string(targetMatrixBody)
	mustContain(t, targetMatrix, "| claude | packaged_runtime | hook_runtime | optional | plugin | marketplace or local plugin install |")
	mustContain(t, targetMatrix, "production-ready package+runtime lane")
	mustContain(t, targetMatrix, "package-only config lane plus public-stable stable-subset runtime")
	mustContain(t, targetMatrix, "without launcher.yaml, and optionally add launcher-backed hooks runtime surfaces")
	mustContain(t, targetMatrix, "| codex-package | packaged_runtime | plugin_package | ignored | plugin | plugin directory or marketplace cache |")
	mustContain(t, targetMatrix, "| codex-runtime | packaged_runtime | local_runtime_integration | required | plugin | repo-local config wiring |")
	mustContain(t, targetMatrix, "| gemini | extension_package | mcp_extension | optional | extension | copy install | link | restart required | ~/.gemini/extensions/<name> | production-ready extension packaging lane |")
	mustContain(t, targetMatrix, "production-ready extension packaging plus optional production-ready 9-hook Go runtime")
	mustContain(t, targetMatrix, "| cursor | ide_plugin | plugin_package | ignored | plugin | marketplace or /add-plugin install | package authoring workspace | plugin reload or restart | .cursor-plugin/plugin.json | packaging-only target | Cursor marketplace plugin bundle with portable skills and optional portable MCP |")
	mustContain(t, targetMatrix, "| cursor-workspace | code_plugin | workspace_config_lane | ignored | workspace | workspace config files | config authoring workspace | config reload or restart | .cursor/mcp.json | packaging-only target | workspace-config lane with first-class MCP config and project rules |")
	mustContain(t, targetMatrix, "| opencode | code_plugin | workspace_config_lane | ignored | workspace | workspace config file | config authoring workspace | config reload or restart | opencode.json | packaging-only target | workspace-config lane with first-class npm plugin refs including tuple-form options, MCP, skills, commands, agents, default_agent, instructions, permission, themes, beta standalone tools with dedicated live evidence, stable official-style local JS/TS plugins plus shared dependency metadata, JSON/JSONC native import, explicit user-scope import, and sanctioned config.extra passthrough for broader product config |")
	mustContain(t, targetMatrix, "mcp=stable, rules=stable")
	mustContain(t, targetMatrix, "package_metadata, interface, hooks, manifest_extra, app_manifest")
	mustContain(t, targetMatrix, "package_metadata=plugin/targets/codex-package/package.yaml")
	mustContain(t, targetMatrix, "interface=plugin/targets/codex-package/interface.json")
	mustContain(t, targetMatrix, "config_extra=plugin/targets/codex-runtime/config.extra.toml")
	mustContain(t, targetMatrix, "interface=stable, hooks=stable, manifest_extra=stable, app_manifest=beta")
	mustContain(t, targetMatrix, ".app.json (when app_manifest is enabled)")
	mustContain(t, targetMatrix, "hooks/** (when hooks are authored)")
	mustContain(t, targetMatrix, ".mcp.json (when portable MCP is authored)")
	mustContain(t, targetMatrix, "commands/** (when commands are authored)")
	mustContain(t, targetMatrix, "| gemini | extension_package | mcp_extension | optional | extension | copy install | link | restart required | ~/.gemini/extensions/<name> | production-ready extension packaging lane |")
	mustContain(t, targetMatrix, "| cursor | ide_plugin | plugin_package | ignored | plugin | marketplace or /add-plugin install | package authoring workspace | plugin reload or restart | .cursor-plugin/plugin.json | packaging-only target | Cursor marketplace plugin bundle with portable skills and optional portable MCP |")
	mustContain(t, targetMatrix, "| cursor-workspace | code_plugin | workspace_config_lane | ignored | workspace | workspace config files | config authoring workspace | config reload or restart | .cursor/mcp.json | packaging-only target | workspace-config lane with first-class MCP config and project rules |")
	mustContain(t, targetMatrix, "| opencode | code_plugin | workspace_config_lane | ignored | workspace | workspace config file | config authoring workspace | config reload or restart | opencode.json | packaging-only target | workspace-config lane with first-class npm plugin refs including tuple-form options, MCP, skills, commands, agents, default_agent, instructions, permission, themes, beta standalone tools with dedicated live evidence, stable official-style local JS/TS plugins plus shared dependency metadata, JSON/JSONC native import, explicit user-scope import, and sanctioned config.extra passthrough for broader product config |")
	mustContain(t, targetMatrix, "mcp=stable, rules=stable")
	mustContain(t, targetMatrix, ".cursor-plugin/plugin.json, skills/** (when portable skills are authored), .mcp.json (when portable MCP is authored)")
	mustContain(t, targetMatrix, ".cursor/mcp.json (when portable MCP is authored), .cursor/rules/** (when rules are authored)")
	mustContain(t, targetMatrix, "config_extra=stable")
	mustContain(t, targetMatrix, "agent_config=stable")
	mustContain(t, targetMatrix, "permission_config=stable")
	mustContain(t, targetMatrix, "instructions_config=stable")
	mustContain(t, targetMatrix, "default_agent=stable")
	mustContain(t, targetMatrix, "commands=stable")
	mustContain(t, targetMatrix, "agents=stable")
	mustContain(t, targetMatrix, "themes=stable")
	mustContain(t, targetMatrix, "tools=beta")
	mustContain(t, targetMatrix, "modes=unsupported")
	mustContain(t, targetMatrix, "local_plugin_code=stable")
	mustContain(t, targetMatrix, "custom_tools=beta")
	mustContain(t, targetMatrix, "local_plugin_dependencies=stable")

	cmd := exec.Command(pluginKitAIBin, "capabilities", "--mode", "runtime", "--format", "json")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("capabilities json: %v\n%s", err, out)
	}
	var entries []map[string]any
	if err := json.Unmarshal(out, &entries); err != nil {
		t.Fatalf("parse capabilities json: %v\n%s", err, out)
	}
	byKey := map[string]map[string]any{}
	for _, entry := range entries {
		key := entry["platform"].(string) + "/" + entry["event"].(string)
		byKey[key] = entry
	}
	assertCapabilityContract(t, byKey, "claude/Stop", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "claude/PreToolUse", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "claude/UserPromptSubmit", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "codex/Notify", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "claude/SessionStart", "beta", "runtime-supported but not stable")
	assertCapabilityContract(t, byKey, "gemini/SessionStart", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/SessionEnd", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/BeforeModel", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/AfterModel", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/BeforeToolSelection", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/BeforeAgent", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/AfterAgent", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/BeforeTool", "stable", "production-ready")
	assertCapabilityContract(t, byKey, "gemini/AfterTool", "stable", "production-ready")

	rootReadme, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	cliReadme, err := os.ReadFile(filepath.Join(root, "cli", "plugin-kit-ai", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	publishGuideEn, err := os.ReadFile(filepath.Join(root, "website", "source", "en", "guide", "how-to-publish-plugins.md"))
	if err != nil {
		t.Fatal(err)
	}
	publishGuideRu, err := os.ReadFile(filepath.Join(root, "website", "source", "ru", "guide", "how-to-publish-plugins.md"))
	if err != nil {
		t.Fatal(err)
	}
	guideIndexEn, err := os.ReadFile(filepath.Join(root, "website", "source", "en", "guide", "index.md"))
	if err != nil {
		t.Fatal(err)
	}
	guideIndexRu, err := os.ReadFile(filepath.Join(root, "website", "source", "ru", "guide", "index.md"))
	if err != nil {
		t.Fatal(err)
	}
	pluginsExamplesReadme, err := os.ReadFile(filepath.Join(root, "examples", "plugins", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	startersExamplesReadme, err := os.ReadFile(filepath.Join(root, "examples", "starters", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	localExamplesReadme, err := os.ReadFile(filepath.Join(root, "examples", "local", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	sdkReadme, err := os.ReadFile(filepath.Join(root, "sdk", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	sdkStabilityDoc, err := os.ReadFile(filepath.Join(root, "sdk", "STABILITY.md"))
	if err != nil {
		t.Fatal(err)
	}
	architectureDoc, err := os.ReadFile(filepath.Join(root, "docs", "ARCHITECTURE.md"))
	if err != nil {
		t.Fatal(err)
	}
	supportDoc, err := os.ReadFile(filepath.Join(root, "docs", "SUPPORT.md"))
	if err != nil {
		t.Fatal(err)
	}
	statusDoc, err := os.ReadFile(filepath.Join(root, "docs", "STATUS.md"))
	if err != nil {
		t.Fatal(err)
	}
	auditDoc, err := os.ReadFile(filepath.Join(root, "docs", "V0_9_AUDIT.md"))
	if err != nil {
		t.Fatal(err)
	}
	hardeningDoc, err := os.ReadFile(filepath.Join(root, "docs", "V1_0_X_HARDENING.md"))
	if err != nil {
		t.Fatal(err)
	}
	productionDoc, err := os.ReadFile(filepath.Join(root, "docs", "PRODUCTION.md"))
	if err != nil {
		t.Fatal(err)
	}
	interpretedPromotionDoc, err := os.ReadFile(filepath.Join(root, "docs", "INTERPRETED_STABLE_SUBSET_AUDIT.md"))
	if err != nil {
		t.Fatal(err)
	}
	opencodePromotionDoc, err := os.ReadFile(filepath.Join(root, "docs", "OPENCODE_STABLE_PROMOTION_AUDIT.md"))
	if err != nil {
		t.Fatal(err)
	}
	opencodeToolsBetaDoc, err := os.ReadFile(filepath.Join(root, "docs", "OPENCODE_TOOLS_BETA_AUDIT.md"))
	if err != nil {
		t.Fatal(err)
	}
	releaseDoc, err := os.ReadFile(filepath.Join(root, "docs", "RELEASE.md"))
	if err != nil {
		t.Fatal(err)
	}
	releaseChecklist, err := os.ReadFile(filepath.Join(root, "docs", "RELEASE_CHECKLIST.md"))
	if err != nil {
		t.Fatal(err)
	}
	releaseNotesTemplate, err := os.ReadFile(filepath.Join(root, "docs", "RELEASE_NOTES_TEMPLATE.md"))
	if err != nil {
		t.Fatal(err)
	}
	rehearsalTemplate, err := os.ReadFile(filepath.Join(root, "docs", "REHEARSAL_TEMPLATE.md"))
	if err != nil {
		t.Fatal(err)
	}
	repoTestsReadme, err := os.ReadFile(filepath.Join(root, "repotests", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	makefile, err := os.ReadFile(filepath.Join(root, "Makefile"))
	if err != nil {
		t.Fatal(err)
	}
	polyglotWorkflow, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "polyglot-smoke.yml"))
	if err != nil {
		t.Fatal(err)
	}

	// The root README separates the installer and unreleased standard preview
	// from preserved v1 capabilities. Keep legacy claims inside that boundary.
	currentReadme, historicalReadme, found := cutHistoricalReadme(string(rootReadme))
	if !found {
		t.Fatal("README missing historical authoring boundary")
	}
	mustContain(t, currentReadme, "## Use plugins")
	mustContain(t, currentReadme, "## Build plugins — unreleased preview")
	currentProse := strings.Join(strings.Fields(currentReadme), " ")
	mustContain(t, currentProse, "root `plugin.json` with optional `skills/` and `mcp.json`")
	mustContain(t, currentProse, "`agentplugins author` and `plugin-kit-ai` are the two prepared entrypoints to one standard authoring engine.")
	mustContain(t, currentProse, "Public deployment remains gated on release acceptance")
	mustContain(t, currentProse, "There is no implicit YAML fallback or second supported YAML engine.")
	mustContain(t, historicalReadme, "[Historical plugin-kit-ai v1, baseline 1.2.4](website/source/en/legacy/v1/index.md)")
	mustContain(t, historicalReadme, "Project migration is not available in v2 yet.")
	mustContain(t, historicalReadme, "Maintain legacy projects using the v1 1.2.4 command set.")
	mustContain(t, strings.Join(strings.Fields(historicalReadme), " "), "All commands, stability labels, and supported-output claims in this section describe the preserved v1 workflow, not the unreleased standard authoring MVP.")
	mustContain(t, historicalReadme, "Build one plugin and ship it to many AI agents was the legacy authoring goal.")
	mustContain(t, string(sdkReadme), "`(*plugin-kit-ai.App).Gemini()`")
	mustContain(t, string(sdkReadme), "`github.com/777genius/plugin-kit-ai/sdk/gemini`")
	mustContain(t, string(sdkReadme), "## Gemini Example")
	mustContain(t, string(sdkReadme), "app.Gemini().OnBeforeTool")
	mustContain(t, string(sdkReadme), "return gemini.BeforeToolContinue()")
	mustContain(t, string(sdkReadme), "Gemini helper rule of thumb:")
	mustContain(t, string(sdkReadme), "Gemini treats `SessionStart` and `SessionEnd` as advisory hooks")
	mustContain(t, string(sdkReadme), "use `gemini.SessionStartMessage(...)` and `gemini.SessionEndMessage(...)`")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeToolSelectionConfig(...)` when you want to steer Gemini tool choice")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeToolSelectionAllowOnly(...)` when you want an allowlist in the vendor-accepted `ANY` shape")
	mustContain(t, string(sdkReadme), "`gemini.BeforeToolSelectionQuiet()` when you only want to suppress hook metadata")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeAgentAddContext(...)` when you want turn-local prompt context")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeAgentStop(...)` when you want to stop the turn but keep the prompt in history")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeAgentDeny(...)` to reject a turn and discard the prompt")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeToolAllow()` or `gemini.AfterToolAllow()` only when you intentionally want an explicit")
	mustContain(t, string(sdkReadme), "use `gemini.BeforeToolRewriteInputValue(...)` when you want to rewrite `tool_input` from a normal Go map/struct")
	mustContain(t, string(sdkReadme), "use `gemini.AfterToolAddContext(...)` to append extra text to the tool result")
	mustContain(t, string(sdkReadme), "`gemini/BeforeToolSelection`")
	mustContain(t, string(sdkReadme), "`gemini/BeforeAgent`")
	mustContain(t, string(sdkReadme), "`gemini/BeforeTool`")
	mustContain(t, string(sdkStabilityDoc), "approved exported Gemini helper constructors for the stable 9-hook runtime surface")
	mustContain(t, string(sdkStabilityDoc), "`SessionStartMessage`")
	mustContain(t, string(sdkStabilityDoc), "`SessionEndMessage`")
	mustContain(t, string(sdkStabilityDoc), "`AfterModelStop`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeAgentStop`")
	mustContain(t, string(sdkStabilityDoc), "`AfterAgentStop`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolStop`")
	mustContain(t, string(sdkStabilityDoc), "`AfterToolStop`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelection`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelectionConfig`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelectionQuiet`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelectionAllowOnly`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelectionForceAny`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelectionForceAuto`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolSelectionDisableAll`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeAgent`")
	mustContain(t, string(sdkStabilityDoc), "`AfterAgent`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeAgentAddContext`")
	mustContain(t, string(sdkStabilityDoc), "`AfterAgentClearContext`")
	mustContain(t, string(sdkStabilityDoc), "`BeforeToolRewriteInputValue`")
	mustContain(t, string(sdkStabilityDoc), "`AfterToolAddContext`")
	mustContain(t, string(sdkStabilityDoc), "`AfterToolTailCallValue`")
	mustContain(t, string(architectureDoc), "`sdk/gemini`")
	mustContain(t, string(architectureDoc), "`sdk/internal/platforms/gemini`")
	mustContain(t, string(architectureDoc), "Gemini runtime hooks use `stdin_json`")
	mustContain(t, historicalReadme, "`plugin-kit-ai` keeps authored source under `plugin/`, generates the supported outputs you need, and helps you validate the repo before handoff.")
	mustContain(t, historicalReadme, "supported outputs for Claude, Codex, Gemini, Cursor, and OpenCode where the repo shape allows it")
	mustContain(t, historicalReadme, "The honest promise is `one repo / many supported outputs`, not fake parity everywhere")
	mustContain(t, historicalReadme, "overview: [plugin-kit-ai documentation](https://github.com/777genius/universal-agent-plugins/blob/9beca10448ac50fbe526a52101d1433a12471980/website/source/en/index.md)")
	mustContain(t, historicalReadme, "fastest start: [Quickstart](https://github.com/777genius/universal-agent-plugins/blob/9beca10448ac50fbe526a52101d1433a12471980/website/source/en/guide/quickstart.md)")
	mustContain(t, historicalReadme, "choose by job first: [Choose What You Are Building](https://github.com/777genius/universal-agent-plugins/blob/9beca10448ac50fbe526a52101d1433a12471980/website/source/en/guide/choose-what-you-are-building.md)")
	mustContain(t, historicalReadme, "one repo, many outputs: [What You Can Build](https://github.com/777genius/universal-agent-plugins/blob/9beca10448ac50fbe526a52101d1433a12471980/website/source/en/guide/what-you-can-build.md)")
	mustContain(t, historicalReadme, "honest caveat: [Support Boundary](https://github.com/777genius/universal-agent-plugins/blob/9beca10448ac50fbe526a52101d1433a12471980/website/source/en/reference/support-boundary.md)")
	mustContain(t, historicalReadme, "## Choose What You Are Building")
	mustContain(t, historicalReadme, "### Connect an online service")
	mustContain(t, historicalReadme, "### Connect a local tool")
	mustContain(t, historicalReadme, "### Build custom plugin logic")
	mustContain(t, historicalReadme, "## Historical Quick Start")
	mustContain(t, historicalReadme, "brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai")
	mustContain(t, historicalReadme, "npm: `npm i -g plugin-kit-ai@1.2.4` or `npx plugin-kit-ai@1.2.4 ...`")
	mustContain(t, historicalReadme, "pipx (`public-beta`, only when that release is published to PyPI): `pipx install plugin-kit-ai==1.2.4`")
	mustContain(t, historicalReadme, "fallback installer: `curl -fsSL https://raw.githubusercontent.com/777genius/plugin-kit-ai/main/scripts/install.sh | sh`")
	mustContain(t, historicalReadme, "plugin-kit-ai init my-plugin --template online-service")
	mustContain(t, historicalReadme, "plugin-kit-ai init my-plugin --template local-tool")
	mustContain(t, historicalReadme, "plugin-kit-ai init my-plugin --template custom-logic")
	mustContain(t, historicalReadme, "plugin-kit-ai init my-plugin")
	mustContain(t, historicalReadme, "plugin-kit-ai generate .")
	mustContain(t, historicalReadme, "plugin-kit-ai validate . --platform codex-runtime --strict")
	mustContain(t, historicalReadme, "## Works Across Multiple Outputs")
	mustContain(t, historicalReadme, "## What To Do Next")
	mustContain(t, historicalReadme, "## Keep This Rule In Mind")
	mustContain(t, string(cliReadme), "How To Publish Plugins")
	mustContain(t, string(cliReadme), "https://777genius.github.io/plugin-kit-ai/docs/en/guide/how-to-publish-plugins.html")
	mustContain(t, string(publishGuideEn), "codex-marketplace")
	mustContain(t, string(publishGuideEn), "claude-marketplace")
	mustContain(t, string(publishGuideEn), "gemini-gallery")
	mustContain(t, string(publishGuideEn), "publish --all --dry-run")
	mustContain(t, string(publishGuideEn), "Gemini uses plan-and-readiness publication in v1, not local apply.")
	mustContain(t, string(publishGuideRu), "codex-marketplace")
	mustContain(t, string(publishGuideRu), "claude-marketplace")
	mustContain(t, string(publishGuideRu), "gemini-gallery")
	mustContain(t, string(publishGuideRu), "publish --all --dry-run")
	mustContain(t, string(publishGuideRu), "Gemini в v1 использует plan-and-readiness publication, а не local apply.")
	mustContain(t, string(guideIndexEn), "/en/guide/how-to-publish-plugins")
	mustContain(t, string(guideIndexRu), "/ru/guide/how-to-publish-plugins")
	mustContain(t, historicalReadme, "## Deep Product Details")
	mustContain(t, historicalReadme, "## Go Deeper By Goal")
	mustContain(t, historicalReadme, "### Fast Local Plugin")
	mustContain(t, historicalReadme, "### Production-Ready Plugin Repo")
	mustContain(t, historicalReadme, "### Already Have Native Config")
	mustContain(t, historicalReadme, "[examples/starters/README.md](examples/starters/README.md)")
	mustContain(t, historicalReadme, "[examples/local/README.md](examples/local/README.md)")
	mustContain(t, historicalReadme, "[docs/CHOOSING_HELPER_DELIVERY_MODE.md](docs/CHOOSING_HELPER_DELIVERY_MODE.md)")
	mustContain(t, historicalReadme, "the stable local Python and Node subset on `codex-runtime` and `claude`")
	mustContain(t, historicalReadme, "`doctor`, `bootstrap`, `validate --strict`, `export`, and bundle handoff for that stable local subset")
	mustContain(t, historicalReadme, "`generate`, `import`, and `normalize` are still `public-beta`")
	mustContain(t, historicalReadme, "[docs/generated/target_support_matrix.md](docs/generated/target_support_matrix.md)")
	mustContain(t, historicalReadme, "[docs/generated/support_matrix.md](docs/generated/support_matrix.md)")
	mustContain(t, historicalReadme, "[docs/SUPPORT.md](docs/SUPPORT.md)")
	mustContain(t, historicalReadme, "## SDK And CLI")
	mustContain(t, historicalReadme, "Go SDK packages:")
	mustContain(t, historicalReadme, "`github.com/777genius/plugin-kit-ai/sdk/claude`")
	mustContain(t, historicalReadme, "`github.com/777genius/plugin-kit-ai/sdk/codex`")
	mustContain(t, historicalReadme, "`github.com/777genius/plugin-kit-ai/sdk/gemini`")
	mustContain(t, historicalReadme, "./bin/plugin-kit-ai doctor ./my-plugin")
	mustContain(t, historicalReadme, "./bin/plugin-kit-ai bootstrap ./my-plugin")
	mustContain(t, historicalReadme, "./bin/plugin-kit-ai import ./native-plugin --from codex-runtime")
	mustContain(t, historicalReadme, "./bin/plugin-kit-ai capabilities --format json")
	mustContain(t, historicalReadme, "`plugin-kit-ai validate --format json` now emits the versioned `plugin-kit-ai/validate-report` contract")
	mustContain(t, historicalReadme, "[docs/CODEX_TARGET_BOUNDARY.md](docs/CODEX_TARGET_BOUNDARY.md)")
	mustContain(t, historicalReadme, "[docs/VALIDATE_JSON_CONTRACT.md](docs/VALIDATE_JSON_CONTRACT.md)")
	mustContain(t, string(cliReadme), "## Fast Local Plugin")
	mustContain(t, string(cliReadme), "## Production-Ready Plugin Repo")
	mustContain(t, string(cliReadme), "## Already Have Native Config")
	mustContain(t, string(cliReadme), "| local notify/runtime plugin in your repo | `codex-runtime` |")
	mustContain(t, string(cliReadme), "| Cursor plugin package lane | `cursor` |")
	mustContain(t, string(cliReadme), "Fast starter repos: [../../examples/starters/README.md](../../examples/starters/README.md)")
	mustContain(t, string(cliReadme), "Reference repos: [../../examples/local/README.md](../../examples/local/README.md)")
	mustContain(t, string(cliReadme), "Helper delivery modes: [../../docs/CHOOSING_HELPER_DELIVERY_MODE.md](../../docs/CHOOSING_HELPER_DELIVERY_MODE.md)")
	mustContain(t, string(cliReadme), "Official starter templates:")
	mustContain(t, string(cliReadme), "https://github.com/777genius/plugin-kit-ai-starter-codex-go")
	mustContain(t, string(cliReadme), "https://github.com/777genius/plugin-kit-ai-starter-codex-python")
	mustContain(t, string(cliReadme), "https://github.com/777genius/plugin-kit-ai-starter-codex-node-typescript")
	mustContain(t, string(cliReadme), "https://github.com/777genius/plugin-kit-ai-starter-claude-go")
	mustContain(t, string(cliReadme), "https://github.com/777genius/plugin-kit-ai-starter-claude-python")
	mustContain(t, string(cliReadme), "https://github.com/777genius/plugin-kit-ai-starter-claude-node-typescript")
	mustContain(t, string(cliReadme), "Gemini defaults to launcher-less packaging but also supports `--runtime go` for the promoted 9-hook runtime lane")
	mustContain(t, string(cliReadme), "`plugin-kit-ai capabilities` defaults to the target/package view")
	mustContain(t, string(cliReadme), "Canonical repo: `github.com/777genius/plugin-kit-ai`.")
	mustContain(t, string(cliReadme), "submodule `github.com/777genius/plugin-kit-ai/cli`")
	mustContain(t, string(cliReadme), "builds the **`plugin-kit-ai`** binary: `init`, `bootstrap`, `doctor`, `dev`, `test`, `export`, `bundle install`, `bundle fetch`, `bundle publish`, `generate`, `import`, `inspect`, `normalize`, `validate`, `capabilities`, `install`, `version`, plus experimental `skills` authoring commands")
	mustContain(t, string(cliReadme), "`plugin-kit-ai bootstrap` is the stable repo-local first-run helper for `python` and `node` launcher-based projects on `codex-runtime` and `claude`")
	mustContain(t, string(cliReadme), "`plugin-kit-ai doctor` is the stable read-only readiness check for `python` and `node` launcher-based projects on `codex-runtime` and `claude`")
	mustContain(t, string(cliReadme), "`plugin-kit-ai validate --format json` emits the versioned `plugin-kit-ai/validate-report` contract")
	mustContain(t, string(cliReadme), "[../../docs/VALIDATE_JSON_CONTRACT.md](../../docs/VALIDATE_JSON_CONTRACT.md)")
	mustContain(t, string(cliReadme), "[../../docs/CODEX_TARGET_BOUNDARY.md](../../docs/CODEX_TARGET_BOUNDARY.md)")
	mustContain(t, string(cliReadme), "requires `.codex-plugin/` to contain only `plugin.json`")
	mustContain(t, string(cliReadme), "keeps `.app.json` / `.mcp.json` as managed root sidecars only when `.codex-plugin/plugin.json` references them")
	mustContain(t, string(cliReadme), "`plugin-kit-ai export` is the stable portable handoff surface for `python` and `node` launcher-based projects on `codex-runtime` and `claude`")
	mustContain(t, string(cliReadme), "`plugin-kit-ai bundle install` is the stable local bundle installer for exported Python/Node handoff archives")
	mustContain(t, string(cliReadme), "`plugin-kit-ai bundle fetch` is the stable remote bundle fetch/install companion for exported Python/Node handoff archives")
	mustContain(t, string(cliReadme), "`plugin-kit-ai bundle publish` is the stable GitHub Releases publish companion for exported Python/Node handoff archives")
	mustContain(t, string(cliReadme), "dedicated opt-in real CLI runtime smoke via `make test-gemini-runtime-live`")
	mustContain(t, string(cliReadme), "`plugin-kit-ai-runtime` on PyPI and npm")
	mustContain(t, string(cliReadme), "./bin/plugin-kit-ai init my-plugin --platform codex-runtime --runtime python --runtime-package --runtime-package-version "+runtimePackageVersion)
	mustContain(t, string(cliReadme), "./bin/plugin-kit-ai init my-plugin --platform codex-runtime --runtime node --typescript --runtime-package --runtime-package-version "+runtimePackageVersion)
	mustContain(t, string(cliReadme), "Released CLIs auto-pin `plugin-kit-ai-runtime` to their own stable tag and print the chosen helper dependency; development builds require `--runtime-package-version`.")
	mustContain(t, string(cliReadme), "Supported bootstrap paths for the CLI itself:")
	mustContain(t, string(cliReadme), "brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai")
	mustContain(t, string(cliReadme), "pipx install plugin-kit-ai")
	mustContain(t, string(cliReadme), "`npm i -g plugin-kit-ai` or `npx plugin-kit-ai@latest ...`")
	mustContain(t, string(cliReadme), "recommended CLI bootstrap")
	mustContain(t, string(cliReadme), "official pipx CLI bootstrap when a release is published to PyPI (`public-beta`)")
	mustContain(t, string(cliReadme), "`scripts/install.sh` resolves the latest published stable release by default")
	mustContain(t, string(cliReadme), "`777genius/universal-agent-plugins/setup-plugin-kit-ai@v1` reuses that same verified release contract")
	mustContain(t, string(cliReadme), "init --extras` on stable interpreted `python`/`node` launcher-based projects emits `.github/workflows/bundle-release.yml`")
	mustContain(t, string(cliReadme), "creates a published release by default")
	mustContain(t, string(cliReadme), "`--draft` as an opt-in safety mode")
	mustContain(t, string(cliReadme), "URL mode verifies `--sha256` or `<url>.sha256`, GitHub Releases mode prefers `checksums.txt` and falls back to `<asset>.sha256`")
	mustContain(t, string(cliReadme), "./bin/plugin-kit-ai import ./native-plugin --from codex-runtime")
	mustContain(t, string(cliReadme), "| `node` | stable local-runtime subset | repo-local on `codex-runtime` and `claude` | lockfile-first manager detection (`bun`, `pnpm`, `yarn`, `npm`); JavaScript by default, TypeScript via `--runtime node --typescript` |")
	mustContain(t, string(cliReadme), "| `shell` | public-beta | repo-local only | POSIX shell on Unix, `bash` in `PATH` on Windows |")
	mustContain(t, string(cliReadme), "Generated Claude/Codex package-runtime config shapes are part of the repo-owned contract surface")
	mustContain(t, string(cliReadme), "fast starter repos, and deeper reference examples live in")
	mustContain(t, string(startersExamplesReadme), "# Canonical Starter Repos")
	mustContain(t, string(startersExamplesReadme), "fastest way to get one working plugin repo that can later expand to more supported outputs")
	mustContain(t, string(startersExamplesReadme), "the starter is the first path, not the final boundary")
	mustContain(t, string(startersExamplesReadme), "brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai")
	mustContain(t, string(startersExamplesReadme), "npm i -g plugin-kit-ai")
	mustContain(t, string(startersExamplesReadme), "pipx install plugin-kit-ai")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai doctor .")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai bootstrap .")
	mustContain(t, string(startersExamplesReadme), "consume `github.com/777genius/plugin-kit-ai/sdk@"+goSDKVersion+"` as a normal module")
	mustContain(t, string(startersExamplesReadme), "go test ./...")
	mustContain(t, string(startersExamplesReadme), "go build -o bin/<starter-name> ./cmd/<starter-name>")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai validate . --platform <codex-runtime|claude> --strict")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai bundle publish . --platform <codex-runtime|claude> --repo owner/repo --tag v1.0.0")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai bundle fetch owner/repo --tag v1.0.0 --platform <codex-runtime|claude> --runtime <python|node> --dest ./handoff-plugin")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai-runtime")
	mustContain(t, string(startersExamplesReadme), "codex-python-runtime-package-starter")
	mustContain(t, string(startersExamplesReadme), "claude-node-typescript-runtime-package-starter")
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai-runtime=="+runtimePackageVersion)
	mustContain(t, string(startersExamplesReadme), "plugin-kit-ai-runtime@"+runtimePackageVersion)
	mustContain(t, string(startersExamplesReadme), "Use this template")
	mustContain(t, string(startersExamplesReadme), "https://github.com/777genius/plugin-kit-ai-starter-codex-go")
	mustContain(t, string(startersExamplesReadme), "https://github.com/777genius/plugin-kit-ai-starter-codex-python")
	mustContain(t, string(startersExamplesReadme), "https://github.com/777genius/plugin-kit-ai-starter-codex-node-typescript")
	mustContain(t, string(startersExamplesReadme), "https://github.com/777genius/plugin-kit-ai-starter-claude-go")
	mustContain(t, string(startersExamplesReadme), "https://github.com/777genius/plugin-kit-ai-starter-claude-python")
	mustContain(t, string(startersExamplesReadme), "https://github.com/777genius/plugin-kit-ai-starter-claude-node-typescript")
	mustContain(t, string(localExamplesReadme), "For copy-first starter repos, see [../starters/README.md](../starters/README.md).")
	mustContain(t, string(localExamplesReadme), "plugin-kit-ai-runtime")
	mustContain(t, string(pluginsExamplesReadme), "# Production Plugin Examples")
	mustContain(t, string(pluginsExamplesReadme), "[cursor-basic](./cursor-basic): Cursor packaged plugin repo with `plugin/plugin.yaml`, portable `plugin/skills/**`, generated `.cursor-plugin/plugin.json`, and shared `.mcp.json`")
	mustContain(t, string(pluginsExamplesReadme), "For copy-first Go/Python/Node starter repos, see [../starters/README.md](../starters/README.md).")
	mustContain(t, string(pluginsExamplesReadme), "For deeper repo-local Python/Node entrance references, including the checked-in helper-layer examples, see [../local/README.md](../local/README.md).")
	mustContain(t, string(pluginsExamplesReadme), "Executable `python` and `node` plugins are stable supported repo-local local-runtime lanes")
	mustContain(t, string(pluginsExamplesReadme), "plugin-kit-ai capabilities --mode runtime --platform gemini")
	mustContain(t, string(pluginsExamplesReadme), "make test-gemini-runtime")
	mustContain(t, string(pluginsExamplesReadme), "make test-gemini-runtime-live")
	mustContain(t, string(repoTestsReadme), "current production-ready 9-hook runtime")
	mustContain(t, string(repoTestsReadme), "make test-gemini-runtime")
	mustContain(t, string(repoTestsReadme), "make test-gemini-runtime-live")
	mustContain(t, string(supportDoc), "Gemini packaging: production-ready official Gemini CLI extension packaging lane")
	mustContain(t, string(supportDoc), "Gemini runtime: optional production-ready 9-hook Go runtime lane")
	mustContain(t, string(supportDoc), "`github.com/777genius/plugin-kit-ai/sdk/gemini`")
	mustContain(t, string(supportDoc), "`(*plugin-kit-ai.App).Gemini`")
	mustContain(t, string(supportDoc), "Stable event surfaces:")
	mustContain(t, string(supportDoc), "dedicated opt-in real CLI runtime smoke")
	mustContain(t, string(supportDoc), "Gemini runtime hooks, plus the Claude/Codex runtime lanes, appear there")
	mustContain(t, string(supportDoc), "Codex runtime: production-ready within the stable `Notify` path")
	mustContain(t, string(supportDoc), "real `codex exec` with explicit `-c notify=...` override still reaches the repository-owned notify hook harness, the checked-in `examples/plugins/codex-basic-prod` runtime also passes that real `codex exec` path after rebuild, the same checked-in runtime example now also passes real `codex mcp get --json` and `codex mcp list --json` when its generated runtime MCP config is projected back through documented `-c mcp_servers...` overrides, real `codex mcp get --json` and `codex mcp list --json` with explicit `-c mcp_servers...` overrides still expose the projected MCP server contract, real `codex mcp add|get|list|remove` also work through an isolated temporary home for both stdio and streamable HTTP servers, those same mutable CLI config-management commands also pass when seeded from the checked-in runtime and package production examples, their auth-seeded variants also pass for those checked-in runtime and package production examples, a generated `codex-package` `.mcp.json` sidecar can be projected into those documented overrides for real `mcp get`, `mcp list`, plus `exec` MCP smoke, that same generated stdio sidecar now also passes real `codex mcp add|get|list|remove` through both isolated and auth-seeded config homes, a synthetic generated HTTP `codex-package` sidecar now also passes that same real `codex mcp add|get|list|remove` path in both isolated and auth-seeded config homes, auth-seeded live `codex mcp login|logout` also now prove the current CLI rejects stdio servers with stable OAuth-only diagnostics while preserving subsequent `get|list|remove`, and auth-seeded live `codex mcp get` plus `codex mcp remove` now also prove the current missing-server behavior after removal: `get` fails, while `remove` stays idempotent")
	mustContain(t, string(supportDoc), "real `codex mcp get --json` and `codex mcp list --json` with explicit `-c mcp_servers...` overrides still expose the projected MCP server contract")
	mustContain(t, string(supportDoc), "current live Codex CLI build (`v0.117.0` in repo evidence), `codex exec`, `codex mcp get`, and `codex mcp list` do not reliably honor project-local `.codex/config.toml`")
	mustContain(t, string(supportDoc), "this now holds both for a synthetic generated runtime workspace and for the checked-in `examples/plugins/codex-basic-prod` runtime example, across `exec`, `mcp get`, and `mcp list`")
	mustContain(t, string(supportDoc), "an isolated `CODEX_HOME` can successfully drive `codex mcp add|get|list|remove`, but a follow-up `codex exec` on that same isolated config currently loses live auth and therefore remains evidence-only")
	mustContain(t, string(supportDoc), "A stronger auth-seeded variant now also proves that copied live auth keeps `codex login status` plus documented stdio and HTTP `mcp add|get|list|remove` flows working inside a temporary `CODEX_HOME`, while the subsequent `codex exec` probe can still skip because the persisted MCP tool is not exposed in that session")
	mustContain(t, string(supportDoc), "helper delivery modes are documented in [CHOOSING_HELPER_DELIVERY_MODE.md](./CHOOSING_HELPER_DELIVERY_MODE.md)")
	mustContain(t, string(supportDoc), "while `init ... --runtime-package` switches to the shared dependency path")
	mustContain(t, string(supportDoc), "development builds accept `--runtime-package-version`")
	mustContain(t, string(productionDoc), "helper delivery tradeoff: see [CHOOSING_HELPER_DELIVERY_MODE.md](./CHOOSING_HELPER_DELIVERY_MODE.md)")
	mustContain(t, string(productionDoc), "dedicated opt-in real CLI runtime smoke")
	mustContain(t, string(productionDoc), "Cursor: packaged plugin target with `.cursor-plugin/plugin.json`, root `skills/**`, and optional shared `.mcp.json`; `cursor-workspace` remains the secondary repo-local `.cursor/` subset when you explicitly need workspace files instead of a package bundle")
	mustContain(t, string(productionDoc), "plugin-kit-ai validate . --platform <claude|codex-runtime|codex-package|cursor|opencode> --strict")
	mustContain(t, string(productionDoc), "Cursor: treat `generate --check` plus `validate --strict` as the packaged plugin readiness gate for `.cursor-plugin/plugin.json`, root `skills/**`, and optional shared `.mcp.json`")
	mustContain(t, string(productionDoc), "## Cursor Packaged Plugin Path")
	mustContain(t, string(productionDoc), "## Cursor Workspace Secondary Path")
	mustContain(t, string(productionDoc), "[examples/plugins/cursor-basic](../examples/plugins/cursor-basic)")
	mustContain(t, string(productionDoc), "development builds should pass `--runtime-package-version`")
	mustContain(t, string(supportDoc), "Codex package: production-ready official plugin package lane")
	mustContain(t, string(supportDoc), "Codex package bundle contract: `.codex-plugin/` contains only `plugin.json`, while optional `.app.json` and `.mcp.json` stay at plugin root and must match manifest refs")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai bootstrap` for `python` and `node` launcher-based projects on `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai doctor` for `python` and `node` launcher-based projects on `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai export` for `python` and `node` launcher-based projects on `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai bundle install` for local exported Python/Node bundles on `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai bundle fetch` for remote exported Python/Node bundles on `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai bundle publish` for GitHub Releases handoff of exported Python/Node bundles on `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "Stable CLI bootstrap/setup path for `plugin-kit-ai` itself:")
	mustContain(t, string(supportDoc), "`brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai` is the recommended package-manager install path")
	mustContain(t, string(supportDoc), "`npm i -g plugin-kit-ai` or `npx plugin-kit-ai@latest ...` is the official JavaScript ecosystem path")
	mustContain(t, string(supportDoc), "when the PyPI wrapper is published for a release, `pipx install plugin-kit-ai` or `pipx run plugin-kit-ai version` is the Python ecosystem path")
	mustContain(t, string(supportDoc), "`scripts/install.sh` resolves the latest published stable release by default")
	mustContain(t, string(supportDoc), "`777genius/universal-agent-plugins/setup-plugin-kit-ai@v1` is the official CI setup action")
	mustContain(t, string(supportDoc), "`plugin-kit-ai-runtime` on PyPI and npm")
	mustContain(t, string(supportDoc), "Current beta CLI commands:")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai bootstrap` for launcher-based `shell` projects")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai doctor` for launcher-based `shell` projects")
	mustContain(t, string(supportDoc), "- `plugin-kit-ai export` for launcher-based `shell` projects")
	mustContain(t, string(supportDoc), "stable local-runtime interpreted subset:")
	mustContain(t, string(supportDoc), "stable scope is scaffold, validate, launcher execution, repo-local bootstrap, read-only doctor checks, bounded portable export bundles, local exported bundle install, remote bundle fetch, and GitHub Releases bundle publish")
	mustContain(t, string(supportDoc), "beta local-runtime remainder:")
	mustContain(t, string(supportDoc), "stable local bundle-install subset:")
	mustContain(t, string(supportDoc), "stable remote bundle-fetch subset:")
	mustContain(t, string(supportDoc), "stable GitHub bundle-publish subset:")
	mustContain(t, string(supportDoc), "community-first downstream setup path:")
	mustContain(t, string(supportDoc), "local recommended install path uses Homebrew")
	mustContain(t, string(supportDoc), "local JS ecosystem install path uses `npm i -g plugin-kit-ai` as `public-beta`")
	mustContain(t, string(supportDoc), "local Python ecosystem install path uses `pipx install plugin-kit-ai` as `public-beta` when that release was published to PyPI")
	mustContain(t, string(supportDoc), "local CLI bootstrap uses `scripts/install.sh`")
	mustContain(t, string(supportDoc), "CI bootstrap uses `777genius/universal-agent-plugins/setup-plugin-kit-ai@v1`")
	mustContain(t, string(supportDoc), "Homebrew tap updates follow successful `Release Assets` completion or a manual tag-scoped rerun")
	mustContain(t, string(supportDoc), "npm publishes follow successful `Release Assets` completion or a manual tag-scoped rerun")
	mustContain(t, string(supportDoc), "PyPI publishes follow successful `Release Assets` completion when trusted publishing is enabled")
	mustContain(t, string(supportDoc), "creates a published release by default; `--draft` keeps the target release as draft")
	mustContain(t, string(releaseDoc), "Go SDK module proxy evidence when the Go SDK public consumption contract changed")
	mustContain(t, string(releaseDoc), "SDK submodule tag: `sdk/vX.Y.Z`")
	mustContain(t, string(releaseDoc), "npm runtime-package publish result")
	mustContain(t, string(releaseDoc), "PyPI runtime-package publish result")
	mustContain(t, string(releaseChecklist), "clean-module `go list -m github.com/777genius/plugin-kit-ai/sdk@vX.Y.Z` recorded")
	mustContain(t, string(releaseChecklist), "clean-module `go get github.com/777genius/plugin-kit-ai/sdk@vX.Y.Z` recorded")
	mustContain(t, string(releaseChecklist), "`plugin-kit-ai-runtime` npm authoring package changed")
	mustContain(t, string(releaseChecklist), "`plugin-kit-ai-runtime` PyPI authoring package changed")
	mustContain(t, string(supportDoc), "supported subset: exported `python` and `node` bundles for `codex-runtime` and `claude`")
	mustContain(t, string(supportDoc), "URL mode verifies `--sha256` or `<url>.sha256`")
	mustContain(t, string(supportDoc), "GitHub Releases mode prefers `checksums.txt` and falls back to `<asset>.sha256`")
	mustContain(t, string(supportDoc), "unsupported scope is universal package-management policy and packaged distribution through `plugin-kit-ai install`")
	mustContain(t, string(supportDoc), "target/package contract matrix")
	mustContain(t, string(supportDoc), "generated Claude/Codex config wiring is a repo-owned contract surface guarded by `generate --check`")
	mustContain(t, string(supportDoc), "OpenCode local plugin loading stable subset is guarded by `generate --check`, strict validation, the production example canary, the documented `test-opencode-live` loader smoke path, and the documented `test-opencode-cli-live` real-model smoke path")
	mustContain(t, string(supportDoc), "OpenCode standalone tools beta subset is guarded by `generate --check`, strict validation, the production example canary, and the documented `test-opencode-tools-live` smoke path")
	mustContain(t, string(supportDoc), "explicit `--include-user-scope` import from `~/.config/opencode`")
	mustContain(t, string(statusDoc), "community-first interpreted stable subset promoted on main")
	mustContain(t, string(statusDoc), "OpenCode stable subset")
	mustContain(t, string(statusDoc), "Community polyglot subset")
	mustContain(t, string(statusDoc), "Codex CLI `v0.117.0` does not reliably honor project-local `.codex/config.toml` for `exec` or `mcp get`")
	mustContain(t, string(statusDoc), "generated `codex-package` `.mcp.json` sidecar preflight exist")
	mustContain(t, string(auditDoc), "generated `codex-package` `.mcp.json` sidecar projection into the same live CLI path")
	mustContain(t, string(interpretedPromotionDoc), "# Interpreted Stable Subset Audit")
	mustContain(t, string(interpretedPromotionDoc), "- `python`: `stable-approved`")
	mustContain(t, string(interpretedPromotionDoc), "- `node`: `stable-approved`")
	mustContain(t, string(interpretedPromotionDoc), "- `plugin-kit-ai bundle install`")
	mustContain(t, string(interpretedPromotionDoc), "- `plugin-kit-ai bundle fetch`")
	mustContain(t, string(interpretedPromotionDoc), "- `plugin-kit-ai bundle publish`")
	mustContain(t, string(interpretedPromotionDoc), "- `bundle install for exported python/node local bundles`: `stable-approved`")
	mustContain(t, string(interpretedPromotionDoc), "- `bundle fetch for exported python/node remote bundles`: `stable-approved`")
	mustContain(t, string(interpretedPromotionDoc), "- `bundle publish for exported python/node GitHub Releases handoff`: `stable-approved`")
	mustContain(t, string(interpretedPromotionDoc), "official downstream CLI availability through Homebrew, the `public-beta` npm wrapper, the `public-beta` PyPI/pipx wrapper, `scripts/install.sh`, and `777genius/universal-agent-plugins/setup-plugin-kit-ai@v1`")
	mustContain(t, string(interpretedPromotionDoc), "`.github/workflows/bundle-release.yml`")
	mustContain(t, string(interpretedPromotionDoc), "- `shell`: `stays-beta`")
	mustContain(t, string(opencodePromotionDoc), "# OpenCode Stable Promotion Audit")
	mustContain(t, string(opencodePromotionDoc), "Standalone-tools beta evidence is tracked separately")
	mustContain(t, string(opencodePromotionDoc), "- `local_plugin_code`: `stable-approved`")
	mustContain(t, string(opencodePromotionDoc), "- `local_plugin_dependencies`: `stable-approved`")
	mustContain(t, string(opencodePromotionDoc), "- `custom_tools`: `stays-beta`")
	mustContain(t, string(opencodePromotionDoc), "first-class standalone `.opencode/tools/**` beyond its documented beta contract")
	mustContain(t, string(opencodeToolsBetaDoc), "# OpenCode Tools Beta Audit")
	mustContain(t, string(opencodeToolsBetaDoc), "- `tools`: `beta-with-live-evidence`")
	mustContain(t, string(opencodeToolsBetaDoc), "dedicated opt-in standalone-tools smoke evidence")
	mustContain(t, string(productionDoc), "Claude: production-ready within the stable `Stop`, `PreToolUse`, and `UserPromptSubmit` event set")
	mustContain(t, string(productionDoc), "Codex runtime: production-ready within the stable `Notify` path")
	mustContain(t, string(productionDoc), "Codex package: production-ready official plugin package lane")
	mustContain(t, string(productionDoc), "first-class beta standalone tools")
	mustContain(t, string(productionDoc), "make test-opencode-tools-live")
	mustContain(t, string(productionDoc), "Node/TypeScript and Python are the stable interpreted subset")
	mustContain(t, string(productionDoc), "After bootstrap, treat `validate --strict` as the CI-grade readiness gate for interpreted runtimes.")
	mustContain(t, string(productionDoc), "`plugin-kit-ai validate --format json`; it emits the versioned `plugin-kit-ai/validate-report` contract with `schema_version: 1`")
	mustContain(t, string(productionDoc), "[VALIDATE_JSON_CONTRACT.md](./VALIDATE_JSON_CONTRACT.md)")
	mustContain(t, string(productionDoc), "[CODEX_TARGET_BOUNDARY.md](./CODEX_TARGET_BOUNDARY.md)")
	mustContain(t, string(productionDoc), "plugin-kit-ai doctor .")
	mustContain(t, string(productionDoc), "plugin-kit-ai export . --platform <codex-runtime|claude>")
	mustContain(t, string(productionDoc), "plugin-kit-ai bundle publish . --platform <codex-runtime|claude> --repo <owner/repo> --tag <tag>")
	mustContain(t, string(productionDoc), "Use Homebrew to install the `plugin-kit-ai` CLI locally when possible")
	mustContain(t, string(productionDoc), "use `npm i -g plugin-kit-ai` as the official `public-beta` JavaScript ecosystem path")
	mustContain(t, string(productionDoc), "use `pipx install plugin-kit-ai` as the `public-beta` Python ecosystem path only when that release was published to PyPI")
	mustContain(t, string(productionDoc), "use `scripts/install.sh` as the verified fallback")
	mustContain(t, string(productionDoc), "`777genius/universal-agent-plugins/setup-plugin-kit-ai@v1`")
	mustContain(t, string(productionDoc), "`.github/workflows/bundle-release.yml`")
	mustContain(t, string(productionDoc), "creates a published release by default")
	mustContain(t, string(productionDoc), "plugin-kit-ai bundle install <bundle.tar.gz> --dest <path>")
	mustContain(t, string(productionDoc), "plugin-kit-ai bundle fetch --url <https://...tar.gz> --dest <path>")
	mustContain(t, string(productionDoc), "URL mode verifies `--sha256` or `<url>.sha256`, GitHub Releases mode prefers `checksums.txt` and falls back to `<asset>.sha256`")
	mustContain(t, string(productionDoc), "plugin-kit-ai import --from codex-runtime")
	mustContain(t, string(productionDoc), "plugin-kit-ai inspect . --target gemini")
	mustContain(t, string(productionDoc), "plugin-kit-ai capabilities --mode runtime --platform gemini")
	mustContain(t, string(productionDoc), "make test-gemini-runtime")
	mustContain(t, string(productionDoc), "make test-gemini-runtime-live")
	validateJSONDoc, err := os.ReadFile(filepath.Join(root, "docs", "VALIDATE_JSON_CONTRACT.md"))
	if err != nil {
		t.Fatal(err)
	}
	codexBoundaryDoc, err := os.ReadFile(filepath.Join(root, "docs", "CODEX_TARGET_BOUNDARY.md"))
	if err != nil {
		t.Fatal(err)
	}
	websitePackageTargetsEN, err := os.ReadFile(filepath.Join(root, "website", "source", "en", "guide", "package-and-workspace-targets.md"))
	if err != nil {
		t.Fatal(err)
	}
	websitePackageTargetsRU, err := os.ReadFile(filepath.Join(root, "website", "source", "ru", "guide", "package-and-workspace-targets.md"))
	if err != nil {
		t.Fatal(err)
	}
	websiteChooseTargetEN, err := os.ReadFile(filepath.Join(root, "website", "source", "en", "guide", "choose-a-target.md"))
	if err != nil {
		t.Fatal(err)
	}
	websiteChooseTargetRU, err := os.ReadFile(filepath.Join(root, "website", "source", "ru", "guide", "choose-a-target.md"))
	if err != nil {
		t.Fatal(err)
	}
	publicationDoctorJSONDoc, err := os.ReadFile(filepath.Join(root, "docs", "PUBLICATION_DOCTOR_JSON_CONTRACT.md"))
	if err != nil {
		t.Fatal(err)
	}
	publicationJSONDoc, err := os.ReadFile(filepath.Join(root, "docs", "PUBLICATION_JSON_CONTRACT.md"))
	if err != nil {
		t.Fatal(err)
	}
	publishJSONDoc, err := os.ReadFile(filepath.Join(root, "docs", "PUBLISH_JSON_CONTRACT.md"))
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(validateJSONDoc), "plugin-kit-ai/validate-report")
	mustContain(t, string(validateJSONDoc), "schema version: `1`")
	mustContain(t, string(validateJSONDoc), "`passed`, `failed`, or `failed_strict_warnings`")
	mustContain(t, string(publicationJSONDoc), "plugin-kit-ai/publication-report")
	mustContain(t, string(publicationJSONDoc), "`warning_count`")
	mustContain(t, string(publicationJSONDoc), "`publication`")
	mustContain(t, string(publishJSONDoc), "plugin-kit-ai/publish-report")
	mustContain(t, string(publishJSONDoc), "`workflow_class`")
	mustContain(t, string(publishJSONDoc), "`needs_repository`")
	mustContain(t, string(publishJSONDoc), "`gemini_origin_remote_missing`")
	mustContain(t, string(publicationDoctorJSONDoc), "plugin-kit-ai/publication-doctor-report")
	mustContain(t, string(publicationDoctorJSONDoc), "`ready`, `needs_channels`, `needs_generate`, `needs_repository`, `needs_sync`, or `inactive`")
	mustContain(t, string(publicationDoctorJSONDoc), "`issue_count`")
	mustContain(t, string(publicationDoctorJSONDoc), "`issues`")
	mustContain(t, string(publicationDoctorJSONDoc), "`local_root`")
	mustContain(t, string(publicationDoctorJSONDoc), "`missing_channel`")
	mustContain(t, string(publicationDoctorJSONDoc), "`missing_package_artifact`")
	mustContain(t, string(publicationDoctorJSONDoc), "`missing_channel_artifact`")
	mustContain(t, string(publicationDoctorJSONDoc), "`drifted_package_artifact`")
	mustContain(t, string(publicationDoctorJSONDoc), "`drifted_channel_artifact`")
	mustContain(t, string(publicationDoctorJSONDoc), "`gemini_origin_remote_missing`")
	mustContain(t, string(publicationDoctorJSONDoc), "`missing_materialized_catalog_entry`")
	mustContain(t, string(publicationDoctorJSONDoc), "exit `0`")
	mustContain(t, string(publicationDoctorJSONDoc), "exit `1`")
	mustContain(t, string(codexBoundaryDoc), "`codex-runtime` is the repo-local notify/runtime lane")
	mustContain(t, string(codexBoundaryDoc), "`codex-package` is the official Codex plugin bundle lane")
	mustContain(t, string(codexBoundaryDoc), "plugin-kit-ai import --from codex-package")
	mustContain(t, string(codexBoundaryDoc), "`.codex-plugin/` must contain only `plugin.json`")
	mustContain(t, string(codexBoundaryDoc), "`.app.json` must exist only when `.codex-plugin/plugin.json` references `./.app.json`")
	mustContain(t, string(codexBoundaryDoc), "`.mcp.json` must exist only when `.codex-plugin/plugin.json` references `./.mcp.json`")
	mustContain(t, string(codexBoundaryDoc), "run the `codex-runtime` and `codex-package` imports separately when a repo contains both native lanes")
	mustContain(t, string(websitePackageTargetsEN), "`.codex-plugin/` contains only `plugin.json`")
	mustContain(t, string(websitePackageTargetsEN), "optional `.app.json` and `.mcp.json` stay at the plugin root")
	mustContain(t, string(websitePackageTargetsRU), "`.codex-plugin/` содержит только `plugin.json`")
	mustContain(t, string(websitePackageTargetsRU), "optional `.app.json` и `.mcp.json` лежат в корне plugin")
	mustContain(t, string(websiteChooseTargetEN), "official `.codex-plugin/plugin.json` bundle layout")
	mustContain(t, string(websiteChooseTargetRU), "официальный bundle layout с `.codex-plugin/plugin.json`")
	mustContain(t, string(cliReadme), "`publication --format json` emits the versioned `plugin-kit-ai/publication-report` contract")
	mustContain(t, string(cliReadme), "`publish --channel codex-marketplace|claude-marketplace --dest <marketplace-root>`")
	mustContain(t, string(cliReadme), "`publish --channel gemini-gallery --dry-run`")
	mustContain(t, string(cliReadme), "`publish --all --dry-run` orchestrates all authored `publish/...` channels in one combined plan")
	mustContain(t, string(cliReadme), "`publish --format json` emits the versioned `plugin-kit-ai/publish-report` contract")
	mustContain(t, string(cliReadme), "`publication doctor --format json` emits `plugin-kit-ai/publication-doctor-report`")
	mustContain(t, string(cliReadme), "`publication doctor --dest <marketplace-root>`")
	mustContain(t, string(cliReadme), "`publication materialize --target codex-package|claude --dest <marketplace-root>`")
	mustContain(t, string(cliReadme), "`publication remove --target codex-package|claude --dest <marketplace-root>`")
	mustContain(t, string(cliReadme), "`--dry-run` on materialize/remove previews those local marketplace mutations without writing")
	mustContain(t, string(hardeningDoc), "beta contract cleanup, change-note hygiene, and documentation follow-through for beta leftovers")
	mustContain(t, string(hardeningDoc), "`python` and `node` are now the stable repo-local subset on `codex-runtime` and `claude`, while `shell` remains `public-beta`")
	mustContain(t, string(hardeningDoc), "local exported bundle install for Python/Node is now part of the promoted stable subset")
	mustContain(t, string(hardeningDoc), "remote bundle fetch for Python/Node is now part of the promoted stable subset")
	mustContain(t, string(hardeningDoc), "GitHub Releases bundle publish for Python/Node is now part of the promoted stable subset")
	mustContain(t, string(releaseDoc), "stable Node/Python doctor/bootstrap/export/bundle-install/bundle-fetch/bundle-publish claims")
	mustContain(t, string(releaseDoc), "the `public-beta` npm wrapper contract")
	mustContain(t, string(releaseDoc), "the `public-beta` PyPI/pipx wrapper contract")
	mustContain(t, string(releaseDoc), "Homebrew tap update result or explicit manual-fallback note")
	mustContain(t, string(releaseDoc), "npm publish result and optional live npm smoke result")
	mustContain(t, string(releaseDoc), "PyPI publish result and optional live pipx smoke result")
	mustContain(t, string(releaseDoc), ".github/workflows/homebrew-tap.yml")
	mustContain(t, string(releaseDoc), "./scripts/update-homebrew-tap.sh")
	mustContain(t, string(releaseDoc), "beta change notes")
	mustContain(t, string(repoTestsReadme), "`PLUGIN_KIT_AI_RUN_GEMINI_CLI=1`")
	mustContain(t, string(repoTestsReadme), "`PLUGIN_KIT_AI_E2E_GEMINI`")
	mustContain(t, string(repoTestsReadme), "`PLUGIN_KIT_AI_SKIP_GEMINI_CLI=1`")
	mustContain(t, string(repoTestsReadme), "`tool_input`/`tool_response`")
	mustContain(t, string(releaseChecklist), "beta change note written when beta user code, scaffold output, readiness semantics, or bundle contents change")
	mustContain(t, string(releaseChecklist), "Homebrew tap update result recorded when the `plugin-kit-ai` CLI install path changed")
	mustContain(t, string(releaseChecklist), "npm publish result recorded when the `plugin-kit-ai` CLI npm channel changed")
	mustContain(t, string(releaseChecklist), "PyPI publish result recorded when the `plugin-kit-ai` CLI Python channel changed")
	mustContain(t, string(releaseChecklist), "stable Node/Python local-runtime, local bundle-install, remote bundle-fetch, or GitHub bundle-publish claims")
	mustContain(t, string(releaseChecklist), "[INTERPRETED_STABLE_SUBSET_AUDIT.md](./INTERPRETED_STABLE_SUBSET_AUDIT.md) updated when the promoted Node/Python local-runtime or bundle-handoff subset changes")
	mustContain(t, string(releaseNotesTemplate), "## Beta Contract Changes")
	mustContain(t, string(releaseNotesTemplate), "- Homebrew tap:")
	mustContain(t, string(releaseNotesTemplate), "- npm publish:")
	mustContain(t, string(releaseNotesTemplate), "- PyPI publish:")
	mustContain(t, string(rehearsalTemplate), "- beta change notes updated:")
	mustContain(t, string(rehearsalTemplate), "`docs/INTERPRETED_STABLE_SUBSET_AUDIT.md` updated when the Node/Python local-runtime stable subset changed:")
	mustContain(t, string(rehearsalTemplate), "- Homebrew tap:")
	mustContain(t, string(rehearsalTemplate), "- npm publish:")
	mustContain(t, string(rehearsalTemplate), "- PyPI publish:")
	mustContain(t, string(makefile), "DoctorReadyNeedsBootstrapNeedsBuildAndBlocked")
	mustContain(t, string(makefile), "BundleInstallInstallsPythonBundleIntoDestination")
	mustContain(t, string(makefile), "BundleInstallRejectsRemoteURL")
	mustContain(t, string(makefile), "BundleFetchURLInstallsPythonBundleWithExplicitChecksum")
	mustContain(t, string(makefile), "BundleFetchGitHubInstallsNodeBundleFromChecksumsTxt")
	mustContain(t, string(makefile), "BundleFetchGitHubUsesLatestRelease")
	mustContain(t, string(makefile), "BundleFetchGitHubRejectsMetadataMismatch")
	mustContain(t, string(makefile), "test-gemini-live:")
	mustContain(t, string(makefile), "PLUGIN_KIT_AI_RUN_GEMINI_CLI=1")
	mustContain(t, string(makefile), "test-gemini-runtime:")
	mustContain(t, string(makefile), "TestInitRunner_geminiGoRuntimeStarter")
	mustContain(t, string(makefile), "TestInspectTextShowsLauncherAndGeminiGuidance")
	mustContain(t, string(makefile), "TestGeminiE2ETracePreservesOriginalRequestName")
	mustContain(t, string(makefile), "TestGeminiE2ETraceCapturesRuntimeLifecycleHooks")
	mustContain(t, string(makefile), "TestGeminiE2ETraceCapturesRuntimeControlSemantics")
	mustContain(t, string(makefile), "test-gemini-runtime-live:")
	mustContain(t, string(makefile), "PLUGIN_KIT_AI_RUN_GEMINI_RUNTIME_LIVE=1")
	mustContain(t, string(makefile), "^TestGeminiCLIRuntime(Hooks|BeforeToolDeny|BeforeModelDeny|DisableAllTools|AfterModelReplaceResponse|AfterAgentRetry|RewriteToolInput)")
	mustContain(t, string(makefile), "test-opencode-live:")
	mustContain(t, string(makefile), "test-opencode-tools-live:")
	mustContain(t, string(makefile), "BootstrapScriptInstallsLatestRelease")
	mustContain(t, string(makefile), "BootstrapScriptSupportsExplicitVersion")
	mustContain(t, string(makefile), "BootstrapScriptRejectsChecksumMismatch")
	mustContain(t, string(makefile), "SetupPluginKitAIActionUsesInstallScript")
	mustContain(t, string(makefile), "NPMCLIPackageContractFiles")
	mustContain(t, string(makefile), "PythonCLIPackageContractFiles")
	mustContain(t, string(makefile), "^TestPythonCLIPackage")
	mustContain(t, string(makefile), "^TestNPMCLIPackage")
	mustContain(t, string(makefile), "InitExtras(PythonEmitsBundleReleaseWorkflow|NodeTypeScriptEmitsBundleReleaseWorkflow)")
	mustContain(t, string(makefile), "BundlePublishCreatesPublishedReleaseByDefault")
	mustContain(t, string(makefile), "BundlePublishCreatesDraftReleaseWhenRequested")
	mustContain(t, string(makefile), "BundlePublishPromotesExistingDraftReleaseToPublished")
	mustContain(t, string(makefile), "BundlePublishReusesExistingDraftReleaseWhenRequested")
	mustContain(t, string(makefile), "BundlePublishReusesExistingPublishedReleaseWithForce")
	mustContain(t, string(makefile), "BundlePublishFailsWhenAssetExistsWithoutForce")
	mustContain(t, string(makefile), "GitHub(ClaudeNodeTypeScriptFlow|LatestClaudeNodeTypeScriptFlow)")
	mustContain(t, string(makefile), "PublishFetch")
	mustContain(t, string(makefile), "BundleInstall")
	mustContain(t, string(makefile), "ClaudeNodeTypeScriptFlow")
	mustContain(t, string(makefile), "BundleFetchURL")
	mustContain(t, string(makefile), "ShellBundleFlow")
	mustContain(t, string(polyglotWorkflow), "DoctorReadyNeedsBootstrapNeedsBuildAndBlocked")
	mustContain(t, string(polyglotWorkflow), "BundleInstallInstallsPythonBundleIntoDestination")
	mustContain(t, string(polyglotWorkflow), "BundleInstallRejectsRemoteURL")
	mustContain(t, string(polyglotWorkflow), "BundleFetchURLInstallsPythonBundleWithExplicitChecksum")
	mustContain(t, string(polyglotWorkflow), "BundleFetchGitHubInstallsNodeBundleFromChecksumsTxt")
	mustContain(t, string(polyglotWorkflow), "BundleFetchGitHubUsesLatestRelease")
	mustContain(t, string(polyglotWorkflow), "BundleFetchGitHubRejectsMetadataMismatch")
	mustContain(t, string(polyglotWorkflow), "BootstrapScriptInstallsLatestRelease")
	mustContain(t, string(polyglotWorkflow), "BootstrapScriptSupportsExplicitVersion")
	mustContain(t, string(polyglotWorkflow), "BootstrapScriptRejectsChecksumMismatch")
	mustContain(t, string(polyglotWorkflow), "SetupPluginKitAIActionUsesInstallScript")
	mustContain(t, string(polyglotWorkflow), "NPMCLIPackageContractFiles")
	mustContain(t, string(polyglotWorkflow), "PythonCLIPackageContractFiles")
	mustContain(t, string(polyglotWorkflow), "^TestNPMCLIPackage")
	mustContain(t, string(polyglotWorkflow), "^TestPythonCLIPackage")
	mustContain(t, string(polyglotWorkflow), "InitExtras(PythonEmitsBundleReleaseWorkflow|NodeTypeScriptEmitsBundleReleaseWorkflow)")

	liveWorkflowBody, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "live.yml"))
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(liveWorkflowBody), "run_homebrew_install")
	mustContain(t, string(liveWorkflowBody), "brew tap 777genius/homebrew-plugin-kit-ai")
	mustContain(t, string(liveWorkflowBody), "brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai")
	mustContain(t, string(liveWorkflowBody), "run_npm_install")
	mustContain(t, string(liveWorkflowBody), "npm i -g --prefix \"${prefix}\" \"plugin-kit-ai@${version}\"")
	mustContain(t, string(liveWorkflowBody), "PLUGIN_KIT_AI_NPM_PREFIX=${prefix}")
	mustContain(t, string(liveWorkflowBody), "npm list -g --prefix \"${PLUGIN_KIT_AI_NPM_PREFIX}\" plugin-kit-ai --depth=0")
	mustContain(t, string(liveWorkflowBody), "\"${PLUGIN_KIT_AI_NPM_PREFIX}/bin/plugin-kit-ai\" version")
	mustContain(t, string(liveWorkflowBody), "run_pipx_install")
	mustContain(t, string(liveWorkflowBody), "python3 -m pipx install --python \"$(command -v python3)\" \"plugin-kit-ai==${version}\"")
	mustContain(t, string(liveWorkflowBody), "\"${PIPX_BIN_DIR}/plugin-kit-ai\" version")
	mustContain(t, string(liveWorkflowBody), "python3 -m pipx run --spec \"plugin-kit-ai==${version}\" plugin-kit-ai version")

	homebrewTapWorkflow, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "homebrew-tap.yml"))
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(homebrewTapWorkflow), "HOMEBREW_TAP_TOKEN")
	mustContain(t, string(homebrewTapWorkflow), "./scripts/update-homebrew-tap.sh")
	mustContain(t, string(homebrewTapWorkflow), "workflow_run:")
	mustContain(t, string(homebrewTapWorkflow), "workflows: [\"Release Assets\"]")
	npmPublishWorkflow, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "npm-publish.yml"))
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(npmPublishWorkflow), "NPM Publish")
	mustContain(t, string(npmPublishWorkflow), "workflow_run:")
	mustContain(t, string(npmPublishWorkflow), "workflows: [\"Release Assets\"]")
	mustContain(t, string(npmPublishWorkflow), "NPM_TOKEN")
	mustContain(t, string(npmPublishWorkflow), "checksums.txt")
	mustContain(t, string(npmPublishWorkflow), "npm publish --access public")
	pypiPublishWorkflow, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "pypi-publish.yml"))
	if err != nil {
		t.Fatal(err)
	}
	mustContain(t, string(pypiPublishWorkflow), "PyPI Publish")
	mustContain(t, string(pypiPublishWorkflow), "workflow_run:")
	mustContain(t, string(pypiPublishWorkflow), "workflows: [\"Release Assets\"]")
	mustContain(t, string(pypiPublishWorkflow), "id-token: write")
	mustContain(t, string(pypiPublishWorkflow), "pypa/gh-action-pypi-publish@release/v1")
	mustContain(t, string(polyglotWorkflow), "BundlePublishCreatesPublishedReleaseByDefault")
	mustContain(t, string(polyglotWorkflow), "BundlePublishCreatesDraftReleaseWhenRequested")
	mustContain(t, string(polyglotWorkflow), "BundlePublishPromotesExistingDraftReleaseToPublished")
	mustContain(t, string(polyglotWorkflow), "BundlePublishReusesExistingDraftReleaseWhenRequested")
	mustContain(t, string(polyglotWorkflow), "BundlePublishReusesExistingPublishedReleaseWithForce")
	mustContain(t, string(polyglotWorkflow), "BundlePublishFailsWhenAssetExistsWithoutForce")
	mustContain(t, string(polyglotWorkflow), "NPMRuntimePackage(ContractFiles|ClaudeAndCodexSmoke)")
	mustContain(t, string(polyglotWorkflow), "PythonRuntimePackage(ContractFiles|ClaudeAndCodexSmoke)")
	mustContain(t, string(polyglotWorkflow), "GitHub(ClaudeNodeTypeScriptFlow|LatestClaudeNodeTypeScriptFlow)")
	mustContain(t, string(polyglotWorkflow), "PublishFetch")
	mustContain(t, string(polyglotWorkflow), "BundleInstall")
	mustContain(t, string(polyglotWorkflow), "ClaudeNodeTypeScriptFlow")
	mustContain(t, string(polyglotWorkflow), "BundleFetchURL")
	mustContain(t, string(polyglotWorkflow), "ShellBundleFlow")

	mustNotContain(t, string(rootReadme), "./bin/plugin-kit-ai validate ./my-plugin --platform codex --strict")
	mustNotContain(t, string(rootReadme), "./bin/plugin-kit-ai init my-plugin --runtime python")
	mustNotContain(t, string(rootReadme), "./bin/plugin-kit-ai import ./native-plugin --from codex\n")
	mustNotContain(t, string(rootReadme), "| `python` | public-beta |")
	mustNotContain(t, string(rootReadme), "| `node` | public-beta |")
	mustNotContain(t, string(cliReadme), "TypeScript via build-to-JS only")
	mustNotContain(t, string(cliReadme), "./bin/plugin-kit-ai import ./native-plugin --from codex\n")
	mustNotContain(t, string(cliReadme), "| `python` | public-beta |")
	mustNotContain(t, string(cliReadme), "| `node` | public-beta |")
	mustNotContain(t, string(cliReadme), "`plugin-kit-ai bundle install` is the `public-beta`")
	mustNotContain(t, string(cliReadme), "`plugin-kit-ai bundle fetch` is the `public-beta`")
	mustNotContain(t, string(cliReadme), "`plugin-kit-ai bundle publish` is the `public-beta`")
	mustNotContain(t, string(cliReadme), "insecure-skip-tls-verify")
	mustNotContain(t, string(rootReadme), "creates a draft release when the tag is missing")
	mustNotContain(t, string(cliReadme), "creates a draft release when the tag is missing")
	mustNotContain(t, string(supportDoc), "missing `--tag` release creates a draft release")
	mustNotContain(t, string(productionDoc), "creates a draft release when the tag is missing")
	mustNotContain(t, string(releaseChecklist), "transition note written")
	mustNotContain(t, string(supportDoc), "should ship with transition guidance")
	mustNotContain(t, string(supportDoc), "local bundle-install beta surface:")

	abiDoc, err := os.ReadFile(filepath.Join(root, "docs", "EXECUTABLE_ABI.md"))
	if err != nil {
		t.Fatal(err)
	}
	installCompatibilityDoc, err := os.ReadFile(filepath.Join(root, "docs", "INSTALL_COMPATIBILITY.md"))
	if err != nil {
		t.Fatal(err)
	}
	mustNotContain(t, string(abiDoc), "creates a draft release when the tag is missing")
	mustContain(t, string(abiDoc), "`plugin-kit-ai validate --strict` is the canonical CI-grade readiness gate for interpreted runtimes")
	mustContain(t, string(abiDoc), "`plugin-kit-ai doctor` is the stable read-only readiness surface for the `python`/`node` local-runtime subset on `codex-runtime` and `claude`; `shell` remains beta")
	mustContain(t, string(abiDoc), "`plugin-kit-ai export` is the stable portable handoff surface for the `python`/`node` local-runtime subset on `codex-runtime` and `claude`; `shell` remains beta")
	mustContain(t, string(abiDoc), "`plugin-kit-ai bundle install` is the stable local bundle installer for exported `python`/`node` handoff bundles")
	mustContain(t, string(abiDoc), "`plugin-kit-ai bundle fetch` is the stable remote handoff companion for exported `python`/`node` bundles")
	mustContain(t, string(abiDoc), "`plugin-kit-ai bundle publish` is the stable GitHub Releases producer-side companion for exported `python`/`node` bundles")
	mustContain(t, string(abiDoc), "creates a published release by default")
	mustContain(t, string(abiDoc), "URL mode verifies `--sha256` or `<url>.sha256`, GitHub Releases mode prefers `checksums.txt` and falls back to `<asset>.sha256`")
	mustContain(t, string(abiDoc), "uses the same runtime lookup order as the generated launcher contract")
	mustContain(t, string(abiDoc), "the recommended package-manager install path is Homebrew: `brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai`")
	mustContain(t, string(abiDoc), "The official JavaScript ecosystem path is `npm i -g plugin-kit-ai` or `npx plugin-kit-ai@latest ...`; this wrapper stays `public-beta`")
	mustContain(t, string(abiDoc), "When a release is published to PyPI, the Python ecosystem path is `pipx install plugin-kit-ai` or `pipx run plugin-kit-ai version`; this wrapper stays `public-beta`")
	mustContain(t, string(abiDoc), "The verified fallback bootstrap path is `scripts/install.sh`, and the official CI setup path is `777genius/universal-agent-plugins/setup-plugin-kit-ai@v1`")
	mustContain(t, string(installCompatibilityDoc), "`brew install 777genius/homebrew-plugin-kit-ai/plugin-kit-ai`")
	mustContain(t, string(installCompatibilityDoc), "`npm i -g plugin-kit-ai` or `npx plugin-kit-ai@latest ...`")
	mustContain(t, string(installCompatibilityDoc), "`pipx install plugin-kit-ai` or `pipx run plugin-kit-ai version`")
	mustContain(t, string(installCompatibilityDoc), "`scripts/install.sh`")
	mustContain(t, string(installCompatibilityDoc), "`777genius/universal-agent-plugins/setup-plugin-kit-ai@v1`")
	mustContain(t, string(installCompatibilityDoc), "Those surfaces install the CLI itself and stay separate from `plugin-kit-ai install`")
	mustContain(t, string(installCompatibilityDoc), "stable local `plugin-kit-ai bundle install` surface, the stable remote `plugin-kit-ai bundle fetch` surface, or the stable GitHub Releases producer companion `plugin-kit-ai bundle publish`")
	mustContain(t, string(abiDoc), "| `python` | stable local-runtime subset | repo-local executable ABI on `codex-runtime` and `claude` | Python `3.10+`; lockfile-first manager detection; `venv`/`requirements`/`uv` expect repo-local `.venv`, `poetry`/`pipenv` can use manager-owned envs |")
	mustContain(t, string(abiDoc), "| `node` | stable local-runtime subset | repo-local executable ABI on `codex-runtime` and `claude` | system Node.js `20+`; JavaScript by default, TypeScript via `--runtime node --typescript` |")
	mustNotContain(t, string(abiDoc), "TypeScript only via build-to-JavaScript")

	help := exec.Command(pluginKitAIBin, "bundle", "fetch", "--help")
	helpOut, err := help.CombinedOutput()
	if err != nil {
		t.Fatalf("bundle fetch help: %v\n%s", err, helpOut)
	}
	mustNotContain(t, string(helpOut), "insecure-skip-tls-verify")
	publishHelp := exec.Command(pluginKitAIBin, "bundle", "publish", "--help")
	publishHelpOut, err := publishHelp.CombinedOutput()
	if err != nil {
		t.Fatalf("bundle publish help: %v\n%s", err, publishHelpOut)
	}
	mustContain(t, string(publishHelpOut), "GitHub Releases")
	mustContain(t, string(publishHelpOut), "--draft")
}

func assertCapabilityContract(t *testing.T, entries map[string]map[string]any, key, wantMaturity, wantContract string) {
	t.Helper()
	entry, ok := entries[key]
	if !ok {
		t.Fatalf("missing capabilities entry %s", key)
	}
	if got := entry["maturity"]; got != wantMaturity {
		t.Fatalf("%s maturity = %v want %q", key, got, wantMaturity)
	}
	if got := entry["contract_class"]; got != wantContract {
		t.Fatalf("%s contract_class = %v want %q", key, got, wantContract)
	}
}

func mustContain(t *testing.T, text, want string) {
	t.Helper()
	if !strings.Contains(text, want) {
		t.Fatalf("missing substring %q\n--- text ---\n%s", want, text)
	}
}

func mustNotContain(t *testing.T, text, want string) {
	t.Helper()
	if strings.Contains(text, want) {
		t.Fatalf("unexpected substring %q\n--- text ---\n%s", want, text)
	}
}
