package app

import (
	"fmt"
	"strings"
)

func validateBundleMetadata(metadata exportMetadata) error {
	if err := validateBundleMetadataEnvelope(metadata); err != nil {
		return err
	}
	return validateBundleMetadataRuntime(metadata)
}

func validateBundleMetadataEnvelope(metadata exportMetadata) error {
	if strings.TrimSpace(metadata.BundleFormat) != "tar.gz" {
		return fmt.Errorf("bundle install supports only plugin-kit-ai export tar.gz bundles")
	}
	if strings.TrimSpace(metadata.GeneratedBy) != "plugin-kit-ai export" {
		return fmt.Errorf("bundle install requires archives generated by plugin-kit-ai export")
	}
	if strings.TrimSpace(metadata.PluginName) == "" {
		return fmt.Errorf("bundle install requires metadata.plugin_name")
	}
	return nil
}

func validateBundleMetadataRuntime(metadata exportMetadata) error {
	switch metadata.Platform {
	case "codex-runtime", "claude":
	default:
		return fmt.Errorf("bundle install supports only codex-runtime or claude bundles; found %q", metadata.Platform)
	}
	switch metadata.Runtime {
	case "python", "node":
	default:
		return fmt.Errorf("bundle install supports only exported python/node bundles; found runtime %q", metadata.Runtime)
	}
	return nil
}
