package platformexec

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/777genius/plugin-kit-ai/cli/internal/pluginmodel"
)

func generateCodexRuntimeArtifacts(root string, graph pluginmodel.PackageGraph, state pluginmodel.TargetState) ([]pluginmodel.Artifact, error) {
	entrypoint := codexRuntimeEntrypoint(graph)
	if strings.TrimSpace(entrypoint) == "" {
		return nil, fmt.Errorf("required launcher missing: %s", pluginmodel.LauncherFileName)
	}
	model, err := loadCodexRuntimeModelHint(root, state)
	if err != nil {
		return nil, err
	}
	configExtra, err := loadNativeExtraDoc(root, state, "config_extra", pluginmodel.NativeDocFormatTOML)
	if err != nil {
		return nil, err
	}
	if err := pluginmodel.ValidateNativeExtraDocConflicts(configExtra, "codex-runtime config.extra.toml", managedKeysForNativeDoc("codex-runtime", "config_extra")); err != nil {
		return nil, err
	}
	var config bytes.Buffer
	config.WriteString("# Generated by plugin-kit-ai. DO NOT EDIT.\n")
	config.WriteString(fmt.Sprintf("model = %q\n", model))
	config.WriteString(fmt.Sprintf("notify = [%q, %q]\n", entrypoint, "notify"))
	if extraBody := pluginmodel.TrimmedExtraBody(configExtra); len(extraBody) > 0 {
		config.WriteByte('\n')
		config.Write(extraBody)
		config.WriteByte('\n')
	}
	artifacts := []pluginmodel.Artifact{{
		RelPath: filepath.Join(".codex", "config.toml"),
		Content: config.Bytes(),
	}}
	copied, err := copyArtifactDirs(root,
		artifactDir{src: authoredComponentDir(state, "commands", filepath.Join("targets", "codex-runtime", "commands")), dst: "commands"},
		artifactDir{src: authoredComponentDir(state, "contexts", filepath.Join("targets", "codex-runtime", "contexts")), dst: "contexts"},
	)
	if err != nil {
		return nil, err
	}
	return append(artifacts, copied...), nil
}

func codexRuntimeEntrypoint(graph pluginmodel.PackageGraph) string {
	if graph.Launcher == nil {
		return ""
	}
	return graph.Launcher.Entrypoint
}

func loadCodexRuntimeModelHint(root string, state pluginmodel.TargetState) (string, error) {
	model := ""
	if meta, ok, err := readYAMLDoc[codexRuntimeMeta](root, state.DocPath("package_metadata")); err != nil {
		return "", fmt.Errorf("parse %s: %w", state.DocPath("package_metadata"), err)
	} else if ok {
		model = strings.TrimSpace(meta.ModelHint)
	}
	if strings.TrimSpace(model) == "" {
		model = "gpt-5.4-mini"
	}
	return model, nil
}
